<?php

namespace Database\Seeders;

use App\Models\Word;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    use WithoutModelEvents;

    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        $now = now();
        $words = collect([
            ['word' => 'apple', 'definition' => 'A round fruit with red, green, or yellow skin.', 'example' => 'She packed an apple for lunch.', 'level' => 'A1', 'part_of_speech' => 'noun'],
            ['word' => 'book', 'definition' => 'A set of written pages that you read.', 'example' => 'He opened the book before class.', 'level' => 'A1', 'part_of_speech' => 'noun'],
            ['word' => 'city', 'definition' => 'A large town where many people live and work.', 'example' => 'The city is busy in the morning.', 'level' => 'A1', 'part_of_speech' => 'noun'],
            ['word' => 'family', 'definition' => 'A group of people related to each other.', 'example' => 'My family eats dinner together.', 'level' => 'A1', 'part_of_speech' => 'noun'],
            ['word' => 'friend', 'definition' => 'A person you like and know well.', 'example' => 'Her friend helped with the homework.', 'level' => 'A1', 'part_of_speech' => 'noun'],
            ['word' => 'happy', 'definition' => 'Feeling good or pleased.', 'example' => 'The children were happy at the party.', 'level' => 'A1', 'part_of_speech' => 'adjective'],
            ['word' => 'listen', 'definition' => 'To give attention to a sound or speaker.', 'example' => 'Please listen to the question carefully.', 'level' => 'A1', 'part_of_speech' => 'verb'],
            ['word' => 'morning', 'definition' => 'The early part of the day.', 'example' => 'I drink water every morning.', 'level' => 'A1', 'part_of_speech' => 'noun'],
            ['word' => 'school', 'definition' => 'A place where students learn.', 'example' => 'They walk to school at eight.', 'level' => 'A1', 'part_of_speech' => 'noun'],
            ['word' => 'water', 'definition' => 'A clear liquid that people drink.', 'example' => 'She drinks water after running.', 'level' => 'A1', 'part_of_speech' => 'noun'],
            ['word' => 'chair', 'definition' => 'A seat for one person.', 'example' => 'The chair is next to the window.', 'level' => 'A1', 'part_of_speech' => 'noun'],
            ['word' => 'door', 'definition' => 'A thing you open to enter or leave a room.', 'example' => 'Please close the door quietly.', 'level' => 'A1', 'part_of_speech' => 'noun'],
            ['word' => 'food', 'definition' => 'Things people or animals eat.', 'example' => 'The food smells good today.', 'level' => 'A1', 'part_of_speech' => 'noun'],
            ['word' => 'house', 'definition' => 'A building where people live.', 'example' => 'Their house has a small garden.', 'level' => 'A1', 'part_of_speech' => 'noun'],
            ['word' => 'mother', 'definition' => 'A female parent.', 'example' => 'My mother works at the hospital.', 'level' => 'A1', 'part_of_speech' => 'noun'],
            ['word' => 'music', 'definition' => 'Sounds made by voices or instruments.', 'example' => 'We listen to music after dinner.', 'level' => 'A1', 'part_of_speech' => 'noun'],
            ['word' => 'phone', 'definition' => 'A device used to call or message people.', 'example' => 'His phone is on the table.', 'level' => 'A1', 'part_of_speech' => 'noun'],
            ['word' => 'picture', 'definition' => 'An image, drawing, or photograph.', 'example' => 'She took a picture of the beach.', 'level' => 'A1', 'part_of_speech' => 'noun'],
            ['word' => 'table', 'definition' => 'A piece of furniture with a flat top.', 'example' => 'Put the keys on the table.', 'level' => 'A1', 'part_of_speech' => 'noun'],
            ['word' => 'work', 'definition' => 'A job or activity that needs effort.', 'example' => 'He goes to work by bus.', 'level' => 'A1', 'part_of_speech' => 'noun'],

            ['word' => 'borrow', 'definition' => 'To use something and give it back later.', 'example' => 'Can I borrow your pen for a minute?', 'level' => 'A2', 'part_of_speech' => 'verb'],
            ['word' => 'careful', 'definition' => 'Taking time to avoid mistakes or danger.', 'example' => 'Be careful when you cross the street.', 'level' => 'A2', 'part_of_speech' => 'adjective'],
            ['word' => 'decide', 'definition' => 'To choose after thinking about options.', 'example' => 'We need to decide where to eat.', 'level' => 'A2', 'part_of_speech' => 'verb'],
            ['word' => 'explain', 'definition' => 'To make something clear or easy to understand.', 'example' => 'The teacher will explain the rule again.', 'level' => 'A2', 'part_of_speech' => 'verb'],
            ['word' => 'healthy', 'definition' => 'Good for your body or not sick.', 'example' => 'A healthy breakfast gives you energy.', 'level' => 'A2', 'part_of_speech' => 'adjective'],
            ['word' => 'improve', 'definition' => 'To become better or make something better.', 'example' => 'Daily practice can improve your English.', 'level' => 'A2', 'part_of_speech' => 'verb'],
            ['word' => 'mistake', 'definition' => 'Something that is not correct.', 'example' => 'I made a mistake in the last sentence.', 'level' => 'A2', 'part_of_speech' => 'noun'],
            ['word' => 'simple', 'definition' => 'Easy to understand or do.', 'example' => 'The instructions are simple and clear.', 'level' => 'A2', 'part_of_speech' => 'adjective'],
            ['word' => 'travel', 'definition' => 'To go from one place to another.', 'example' => 'They travel by train on weekends.', 'level' => 'A2', 'part_of_speech' => 'verb'],
            ['word' => 'weather', 'definition' => 'The temperature, wind, rain, or sun outside.', 'example' => 'The weather is colder today.', 'level' => 'A2', 'part_of_speech' => 'noun'],
            ['word' => 'arrive', 'definition' => 'To reach a place.', 'example' => 'The train will arrive before noon.', 'level' => 'A2', 'part_of_speech' => 'verb'],
            ['word' => 'choose', 'definition' => 'To pick one thing from several options.', 'example' => 'You can choose a topic for homework.', 'level' => 'A2', 'part_of_speech' => 'verb'],
            ['word' => 'describe', 'definition' => 'To say what something or someone is like.', 'example' => 'Can you describe your new apartment?', 'level' => 'A2', 'part_of_speech' => 'verb'],
            ['word' => 'favorite', 'definition' => 'Liked more than others.', 'example' => 'Blue is her favorite color.', 'level' => 'A2', 'part_of_speech' => 'adjective'],
            ['word' => 'invite', 'definition' => 'To ask someone to come to an event.', 'example' => 'They will invite us to the party.', 'level' => 'A2', 'part_of_speech' => 'verb'],
            ['word' => 'journey', 'definition' => 'A trip from one place to another.', 'example' => 'The journey took three hours by car.', 'level' => 'A2', 'part_of_speech' => 'noun'],
            ['word' => 'noisy', 'definition' => 'Making a lot of sound.', 'example' => 'The noisy street made it hard to sleep.', 'level' => 'A2', 'part_of_speech' => 'adjective'],
            ['word' => 'protect', 'definition' => 'To keep someone or something safe.', 'example' => 'A coat can protect you from the rain.', 'level' => 'A2', 'part_of_speech' => 'verb'],
            ['word' => 'repair', 'definition' => 'To fix something that is broken.', 'example' => 'He will repair the bike this weekend.', 'level' => 'A2', 'part_of_speech' => 'verb'],
            ['word' => 'useful', 'definition' => 'Helpful or practical.', 'example' => 'This map is useful in a new city.', 'level' => 'A2', 'part_of_speech' => 'adjective'],

            ['word' => 'achieve', 'definition' => 'To succeed in doing something after effort.', 'example' => 'She worked hard to achieve her goal.', 'level' => 'B1', 'part_of_speech' => 'verb'],
            ['word' => 'benefit', 'definition' => 'A good effect or advantage.', 'example' => 'One benefit of reading is a larger vocabulary.', 'level' => 'B1', 'part_of_speech' => 'noun'],
            ['word' => 'confident', 'definition' => 'Feeling sure about your ability.', 'example' => 'He felt confident before the interview.', 'level' => 'B1', 'part_of_speech' => 'adjective'],
            ['word' => 'manage', 'definition' => 'To control or organize something successfully.', 'example' => 'They manage the project with a small team.', 'level' => 'B1', 'part_of_speech' => 'verb'],
            ['word' => 'opinion', 'definition' => 'What someone thinks or believes about something.', 'example' => 'In my opinion, the plan is realistic.', 'level' => 'B1', 'part_of_speech' => 'noun'],
            ['word' => 'prevent', 'definition' => 'To stop something from happening.', 'example' => 'A helmet can prevent serious injury.', 'level' => 'B1', 'part_of_speech' => 'verb'],
            ['word' => 'reduce', 'definition' => 'To make something smaller or less.', 'example' => 'We should reduce the amount of waste.', 'level' => 'B1', 'part_of_speech' => 'verb'],
            ['word' => 'reliable', 'definition' => 'Able to be trusted or depended on.', 'example' => 'This is a reliable source of information.', 'level' => 'B1', 'part_of_speech' => 'adjective'],
            ['word' => 'struggle', 'definition' => 'To have difficulty doing something.', 'example' => 'Many students struggle with pronunciation.', 'level' => 'B1', 'part_of_speech' => 'verb'],
            ['word' => 'support', 'definition' => 'To help someone or agree with an idea.', 'example' => 'Her parents support her decision.', 'level' => 'B1', 'part_of_speech' => 'verb'],
            ['word' => 'approach', 'definition' => 'A way of doing or thinking about something.', 'example' => 'Her approach to study is very organized.', 'level' => 'B1', 'part_of_speech' => 'noun'],
            ['word' => 'balance', 'definition' => 'A state where different things have the right amount.', 'example' => 'Good balance helps you study and rest.', 'level' => 'B1', 'part_of_speech' => 'noun'],
            ['word' => 'compare', 'definition' => 'To look at two things and see similarities or differences.', 'example' => 'Compare the answers before you choose.', 'level' => 'B1', 'part_of_speech' => 'verb'],
            ['word' => 'develop', 'definition' => 'To grow or become more advanced.', 'example' => 'You can develop confidence through practice.', 'level' => 'B1', 'part_of_speech' => 'verb'],
            ['word' => 'encourage', 'definition' => 'To give someone hope or confidence.', 'example' => 'Teachers encourage students to speak more.', 'level' => 'B1', 'part_of_speech' => 'verb'],
            ['word' => 'focus', 'definition' => 'To give attention to one thing.', 'example' => 'Focus on the words you often forget.', 'level' => 'B1', 'part_of_speech' => 'verb'],
            ['word' => 'involve', 'definition' => 'To include someone or something.', 'example' => 'The task will involve reading and speaking.', 'level' => 'B1', 'part_of_speech' => 'verb'],
            ['word' => 'likely', 'definition' => 'Expected to happen or be true.', 'example' => 'A short review is likely to help.', 'level' => 'B1', 'part_of_speech' => 'adjective'],
            ['word' => 'recognize', 'definition' => 'To know someone or something from before.', 'example' => 'I recognize this word from yesterday.', 'level' => 'B1', 'part_of_speech' => 'verb'],
            ['word' => 'suggest', 'definition' => 'To offer an idea or plan.', 'example' => 'I suggest a shorter practice session.', 'level' => 'B1', 'part_of_speech' => 'verb'],

            ['word' => 'accomplish', 'definition' => 'To complete something successfully.', 'example' => 'The team hopes to accomplish the task today.', 'level' => 'B2', 'part_of_speech' => 'verb'],
            ['word' => 'challenge', 'definition' => 'A difficult task that tests ability.', 'example' => 'Learning ten new words a day is a challenge.', 'level' => 'B2', 'part_of_speech' => 'noun'],
            ['word' => 'consequence', 'definition' => 'A result of an action or situation.', 'example' => 'The consequence of missing practice was clear.', 'level' => 'B2', 'part_of_speech' => 'noun'],
            ['word' => 'estimate', 'definition' => 'To guess an amount based on available information.', 'example' => 'We estimate the lesson will take twenty minutes.', 'level' => 'B2', 'part_of_speech' => 'verb'],
            ['word' => 'evidence', 'definition' => 'Facts or signs that show something is true.', 'example' => 'The report provides evidence for the claim.', 'level' => 'B2', 'part_of_speech' => 'noun'],
            ['word' => 'maintain', 'definition' => 'To keep something at the same level or condition.', 'example' => 'You need regular practice to maintain fluency.', 'level' => 'B2', 'part_of_speech' => 'verb'],
            ['word' => 'negotiate', 'definition' => 'To discuss in order to reach an agreement.', 'example' => 'They negotiate the price before signing.', 'level' => 'B2', 'part_of_speech' => 'verb'],
            ['word' => 'prioritize', 'definition' => 'To decide what is most important.', 'example' => 'Students should prioritize the words they often miss.', 'level' => 'B2', 'part_of_speech' => 'verb'],
            ['word' => 'remarkable', 'definition' => 'Unusual or impressive in a way people notice.', 'example' => 'Her progress this month was remarkable.', 'level' => 'B2', 'part_of_speech' => 'adjective'],
            ['word' => 'sustainable', 'definition' => 'Able to continue for a long time without harm.', 'example' => 'A sustainable study routine is better than cramming.', 'level' => 'B2', 'part_of_speech' => 'adjective'],
            ['word' => 'accurate', 'definition' => 'Correct and without mistakes.', 'example' => 'An accurate answer earns more points.', 'level' => 'B2', 'part_of_speech' => 'adjective'],
            ['word' => 'adapt', 'definition' => 'To change in order to fit a new situation.', 'example' => 'Good learners adapt their routine over time.', 'level' => 'B2', 'part_of_speech' => 'verb'],
            ['word' => 'convince', 'definition' => 'To make someone believe or agree.', 'example' => 'The data can convince them to continue.', 'level' => 'B2', 'part_of_speech' => 'verb'],
            ['word' => 'evaluate', 'definition' => 'To judge the value or quality of something.', 'example' => 'Evaluate your mistakes after each round.', 'level' => 'B2', 'part_of_speech' => 'verb'],
            ['word' => 'framework', 'definition' => 'A basic structure for ideas or work.', 'example' => 'The framework helps organize the lesson.', 'level' => 'B2', 'part_of_speech' => 'noun'],
            ['word' => 'generate', 'definition' => 'To produce or create something.', 'example' => 'The app can generate a new challenge.', 'level' => 'B2', 'part_of_speech' => 'verb'],
            ['word' => 'insight', 'definition' => 'A clear understanding of something.', 'example' => 'The feedback gave her insight into grammar.', 'level' => 'B2', 'part_of_speech' => 'noun'],
            ['word' => 'objective', 'definition' => 'A goal or purpose.', 'example' => 'The objective is to remember words faster.', 'level' => 'B2', 'part_of_speech' => 'noun'],
            ['word' => 'resolve', 'definition' => 'To solve a problem or difficulty.', 'example' => 'They resolve confusion by checking examples.', 'level' => 'B2', 'part_of_speech' => 'verb'],
            ['word' => 'tension', 'definition' => 'A feeling of stress or pressure.', 'example' => 'Time limits add tension to the game.', 'level' => 'B2', 'part_of_speech' => 'noun'],

            ['word' => 'ambiguous', 'definition' => 'Having more than one possible meaning.', 'example' => 'The ambiguous sentence confused the class.', 'level' => 'C1', 'part_of_speech' => 'adjective'],
            ['word' => 'coherent', 'definition' => 'Clear, logical, and easy to understand.', 'example' => 'Her argument was coherent and persuasive.', 'level' => 'C1', 'part_of_speech' => 'adjective'],
            ['word' => 'compelling', 'definition' => 'Very interesting or convincing.', 'example' => 'The speaker gave a compelling reason to continue.', 'level' => 'C1', 'part_of_speech' => 'adjective'],
            ['word' => 'concise', 'definition' => 'Using few words while staying clear.', 'example' => 'A concise answer is often more effective.', 'level' => 'C1', 'part_of_speech' => 'adjective'],
            ['word' => 'deteriorate', 'definition' => 'To become worse over time.', 'example' => 'Without practice, pronunciation can deteriorate.', 'level' => 'C1', 'part_of_speech' => 'verb'],
            ['word' => 'implement', 'definition' => 'To put a plan or system into action.', 'example' => 'The school will implement a new study plan.', 'level' => 'C1', 'part_of_speech' => 'verb'],
            ['word' => 'leverage', 'definition' => 'To use something effectively to get a result.', 'example' => 'You can leverage daily habits to learn faster.', 'level' => 'C1', 'part_of_speech' => 'verb'],
            ['word' => 'mitigate', 'definition' => 'To make a problem less serious.', 'example' => 'Short reviews can mitigate forgetting.', 'level' => 'C1', 'part_of_speech' => 'verb'],
            ['word' => 'resilient', 'definition' => 'Able to recover quickly after difficulty.', 'example' => 'A resilient learner keeps going after mistakes.', 'level' => 'C1', 'part_of_speech' => 'adjective'],
            ['word' => 'substantial', 'definition' => 'Large in amount, value, or importance.', 'example' => 'She made substantial progress in six weeks.', 'level' => 'C1', 'part_of_speech' => 'adjective'],
            ['word' => 'allocate', 'definition' => 'To decide how resources or time should be used.', 'example' => 'Allocate ten minutes to review difficult words.', 'level' => 'C1', 'part_of_speech' => 'verb'],
            ['word' => 'articulate', 'definition' => 'To express an idea clearly.', 'example' => 'She can articulate complex ideas in English.', 'level' => 'C1', 'part_of_speech' => 'verb'],
            ['word' => 'constraint', 'definition' => 'A limit or restriction.', 'example' => 'A time constraint can sharpen your focus.', 'level' => 'C1', 'part_of_speech' => 'noun'],
            ['word' => 'cultivate', 'definition' => 'To develop a skill or habit carefully.', 'example' => 'Cultivate curiosity when you meet new words.', 'level' => 'C1', 'part_of_speech' => 'verb'],
            ['word' => 'diminish', 'definition' => 'To become or make something smaller.', 'example' => 'Regular review can diminish repeated mistakes.', 'level' => 'C1', 'part_of_speech' => 'verb'],
            ['word' => 'formulate', 'definition' => 'To create or prepare something carefully.', 'example' => 'Formulate a sentence before you answer.', 'level' => 'C1', 'part_of_speech' => 'verb'],
            ['word' => 'inherent', 'definition' => 'Existing as a natural part of something.', 'example' => 'There is inherent uncertainty in translation.', 'level' => 'C1', 'part_of_speech' => 'adjective'],
            ['word' => 'pragmatic', 'definition' => 'Focused on practical results.', 'example' => 'A pragmatic plan fits your real schedule.', 'level' => 'C1', 'part_of_speech' => 'adjective'],
            ['word' => 'refine', 'definition' => 'To improve something by making small changes.', 'example' => 'Refine your answer after reading the clue.', 'level' => 'C1', 'part_of_speech' => 'verb'],
            ['word' => 'scrutiny', 'definition' => 'Careful and detailed examination.', 'example' => 'Every example sentence received scrutiny.', 'level' => 'C1', 'part_of_speech' => 'noun'],

            ['word' => 'ephemeral', 'definition' => 'Lasting for only a short time.', 'example' => 'Motivation can be ephemeral without a clear routine.', 'level' => 'C2', 'part_of_speech' => 'adjective'],
            ['word' => 'exacerbate', 'definition' => 'To make a bad situation worse.', 'example' => 'Skipping review can exacerbate memory gaps.', 'level' => 'C2', 'part_of_speech' => 'verb'],
            ['word' => 'incongruous', 'definition' => 'Strange because it does not fit with its surroundings.', 'example' => 'The formal phrase felt incongruous in casual speech.', 'level' => 'C2', 'part_of_speech' => 'adjective'],
            ['word' => 'meticulous', 'definition' => 'Very careful and attentive to detail.', 'example' => 'A meticulous learner checks each pronunciation.', 'level' => 'C2', 'part_of_speech' => 'adjective'],
            ['word' => 'nuance', 'definition' => 'A small but important difference in meaning.', 'example' => 'The nuance between the two verbs is subtle.', 'level' => 'C2', 'part_of_speech' => 'noun'],
            ['word' => 'paradigm', 'definition' => 'A typical model or way of thinking about something.', 'example' => 'Spaced repetition changed the paradigm of memorization.', 'level' => 'C2', 'part_of_speech' => 'noun'],
            ['word' => 'proliferation', 'definition' => 'A rapid increase in the number of something.', 'example' => 'The proliferation of apps gives learners many choices.', 'level' => 'C2', 'part_of_speech' => 'noun'],
            ['word' => 'scrutinize', 'definition' => 'To examine something very carefully.', 'example' => 'Advanced students scrutinize word choice in essays.', 'level' => 'C2', 'part_of_speech' => 'verb'],
            ['word' => 'ubiquitous', 'definition' => 'Present or found everywhere.', 'example' => 'English words are ubiquitous in technology.', 'level' => 'C2', 'part_of_speech' => 'adjective'],
            ['word' => 'unequivocal', 'definition' => 'Clear and leaving no doubt.', 'example' => 'The feedback was unequivocal after the wrong answer.', 'level' => 'C2', 'part_of_speech' => 'adjective'],
            ['word' => 'aberration', 'definition' => 'Something unusual that differs from what is normal.', 'example' => 'One low score was an aberration in her record.', 'level' => 'C2', 'part_of_speech' => 'noun'],
            ['word' => 'conflate', 'definition' => 'To combine two ideas as if they were the same.', 'example' => 'Writers sometimes conflate similar concepts.', 'level' => 'C2', 'part_of_speech' => 'verb'],
            ['word' => 'dissonance', 'definition' => 'A lack of agreement or harmony.', 'example' => 'The phrase created dissonance in the paragraph.', 'level' => 'C2', 'part_of_speech' => 'noun'],
            ['word' => 'intractable', 'definition' => 'Very difficult to control or solve.', 'example' => 'The intractable error required deeper analysis.', 'level' => 'C2', 'part_of_speech' => 'adjective'],
            ['word' => 'labyrinthine', 'definition' => 'Complicated and confusing like a maze.', 'example' => 'The labyrinthine explanation lost the audience.', 'level' => 'C2', 'part_of_speech' => 'adjective'],
            ['word' => 'obfuscate', 'definition' => 'To make something unclear or hard to understand.', 'example' => 'Do not obfuscate a simple argument.', 'level' => 'C2', 'part_of_speech' => 'verb'],
            ['word' => 'perfunctory', 'definition' => 'Done quickly and without real care.', 'example' => 'A perfunctory review rarely fixes weak vocabulary.', 'level' => 'C2', 'part_of_speech' => 'adjective'],
            ['word' => 'quintessential', 'definition' => 'Representing the most typical example.', 'example' => 'That sentence is a quintessential formal opening.', 'level' => 'C2', 'part_of_speech' => 'adjective'],
            ['word' => 'tacit', 'definition' => 'Understood without being directly said.', 'example' => 'The tacit rule was clear from context.', 'level' => 'C2', 'part_of_speech' => 'adjective'],
            ['word' => 'vindicate', 'definition' => 'To prove that someone or something was right.', 'example' => 'The final score can vindicate steady practice.', 'level' => 'C2', 'part_of_speech' => 'verb'],
            ['word' => 'baby', 'definition' => 'A very young child.', 'example' => 'The baby is sleeping in the crib.', 'level' => 'A1', 'part_of_speech' => 'noun'],
            ['word' => 'ball', 'definition' => 'A round object used in games.', 'example' => 'He kicked the ball into the net.', 'level' => 'A1', 'part_of_speech' => 'noun'],
            ['word' => 'bank', 'definition' => 'A place where people keep money.', 'example' => 'She goes to the bank to save money.', 'level' => 'A1', 'part_of_speech' => 'noun'],
            ['word' => 'bath', 'definition' => 'An act of washing the body.', 'example' => 'He takes a hot bath every evening.', 'level' => 'A1', 'part_of_speech' => 'noun'],
            ['word' => 'beer', 'definition' => 'An alcoholic drink made from grain.', 'example' => 'He ordered a cold beer at the bar.', 'level' => 'A1', 'part_of_speech' => 'noun'],
            ['word' => 'bird', 'definition' => 'An animal with feathers and wings.', 'example' => 'A small bird sang on the tree branch.', 'level' => 'A1', 'part_of_speech' => 'noun'],
            ['word' => 'blue', 'definition' => 'A color like the clear sky.', 'example' => 'She wore a beautiful blue dress.', 'level' => 'A1', 'part_of_speech' => 'adjective'],
            ['word' => 'boat', 'definition' => 'A small vehicle for traveling on water.', 'example' => 'They rented a small boat on the lake.', 'level' => 'A1', 'part_of_speech' => 'noun'],
            ['word' => 'body', 'definition' => 'The physical structure of a person.', 'example' => 'Exercise is good for your body.', 'level' => 'A1', 'part_of_speech' => 'noun'],
            ['word' => 'busy', 'definition' => 'Having a lot of things to do.', 'example' => 'The doctor is very busy today.', 'level' => 'A1', 'part_of_speech' => 'adjective'],
            ['word' => 'cake', 'definition' => 'A sweet baked food.', 'example' => 'She made a chocolate cake for his birthday.', 'level' => 'A1', 'part_of_speech' => 'noun'],
            ['word' => 'card', 'definition' => 'A small piece of stiff paper.', 'example' => 'He wrote a birthday card for his mom.', 'level' => 'A1', 'part_of_speech' => 'noun'],
            ['word' => 'cat', 'definition' => 'A small domesticated animal.', 'example' => 'The cat is sleeping on the sofa.', 'level' => 'A1', 'part_of_speech' => 'noun'],
            ['word' => 'cold', 'definition' => 'Having a low temperature.', 'example' => 'The water is too cold to swim in.', 'level' => 'A1', 'part_of_speech' => 'adjective'],
            ['word' => 'coat', 'definition' => 'An outer piece of clothing.', 'example' => 'Put on your coat before going outside.', 'level' => 'A1', 'part_of_speech' => 'noun'],
            ['word' => 'cup', 'definition' => 'A small container used for drinking.', 'example' => 'She drank a cup of hot tea.', 'level' => 'A1', 'part_of_speech' => 'noun'],
            ['word' => 'dark', 'definition' => 'With little or no light.', 'example' => 'The street was dark at midnight.', 'level' => 'A1', 'part_of_speech' => 'adjective'],
            ['word' => 'date', 'definition' => 'A specific day of the month.', 'example' => 'What is the date today?', 'level' => 'A1', 'part_of_speech' => 'noun'],
            ['word' => 'day', 'definition' => 'A period of twenty-four hours.', 'example' => 'It is a beautiful day today.', 'level' => 'A1', 'part_of_speech' => 'noun'],
            ['word' => 'dog', 'definition' => 'A common animal kept as a pet.', 'example' => 'The dog barked at the stranger.', 'level' => 'A1', 'part_of_speech' => 'noun'],
            ['word' => 'draw', 'definition' => 'To make a picture with a pen.', 'example' => 'Children love to draw pictures of animals.', 'level' => 'A1', 'part_of_speech' => 'verb'],
            ['word' => 'drink', 'definition' => 'To take liquid into the mouth.', 'example' => 'Please drink some water.', 'level' => 'A1', 'part_of_speech' => 'verb'],
            ['word' => 'easy', 'definition' => 'Not difficult to do.', 'example' => 'The exam was very easy.', 'level' => 'A1', 'part_of_speech' => 'adjective'],
            ['word' => 'egg', 'definition' => 'An oval object produced by a bird.', 'example' => 'She fried an egg for breakfast.', 'level' => 'A1', 'part_of_speech' => 'noun'],
            ['word' => 'eye', 'definition' => 'The organ of sight.', 'example' => 'She closed her eye during the movie.', 'level' => 'A1', 'part_of_speech' => 'noun'],
            ['word' => 'face', 'definition' => 'The front part of the head.', 'example' => 'She washed her face with warm water.', 'level' => 'A1', 'part_of_speech' => 'noun'],
            ['word' => 'fire', 'definition' => 'Heat and light from burning.', 'example' => 'They sat close to the warm fire.', 'level' => 'A1', 'part_of_speech' => 'noun'],
            ['word' => 'fish', 'definition' => 'An animal that lives in water.', 'example' => 'We saw many fish in the river.', 'level' => 'A1', 'part_of_speech' => 'noun'],
            ['word' => 'game', 'definition' => 'An activity played for fun.', 'example' => 'They played a fun game after dinner.', 'level' => 'A1', 'part_of_speech' => 'noun'],
            ['word' => 'girl', 'definition' => 'A female child.', 'example' => 'The little girl wore a red hat.', 'level' => 'A1', 'part_of_speech' => 'noun'],
            ['word' => 'hair', 'definition' => 'The fine threads on the head.', 'example' => 'She has long brown hair.', 'level' => 'A1', 'part_of_speech' => 'noun'],
            ['word' => 'hand', 'definition' => 'The part of the arm below the wrist.', 'example' => 'He held the cup with his left hand.', 'level' => 'A1', 'part_of_speech' => 'noun'],
            ['word' => 'head', 'definition' => 'The upper part of the body.', 'example' => 'Wear a helmet to protect your head.', 'level' => 'A1', 'part_of_speech' => 'noun'],
            ['word' => 'hot', 'definition' => 'Having a high temperature.', 'example' => 'The soup is very hot today.', 'level' => 'A1', 'part_of_speech' => 'adjective'],
            ['word' => 'kind', 'definition' => 'Friendly and generous.', 'example' => 'She was very kind to the tourist.', 'level' => 'A1', 'part_of_speech' => 'adjective'],
            ['word' => 'land', 'definition' => 'The solid part of the earth.', 'example' => 'The plane landed safely on dry land.', 'level' => 'A1', 'part_of_speech' => 'noun'],
            ['word' => 'life', 'definition' => 'The period of being alive.', 'example' => 'He wants to live a peaceful life.', 'level' => 'A1', 'part_of_speech' => 'noun'],
            ['word' => 'love', 'definition' => 'A strong feeling of affection.', 'example' => 'They showed great love for their pets.', 'level' => 'A1', 'part_of_speech' => 'noun'],
            ['word' => 'milk', 'definition' => 'A white liquid produced by cows.', 'example' => 'He drinks a glass of milk daily.', 'level' => 'A1', 'part_of_speech' => 'noun'],
            ['word' => 'name', 'definition' => 'A word by which a person is known.', 'example' => 'Please write your name here.', 'level' => 'A1', 'part_of_speech' => 'noun'],
            ['word' => 'nice', 'definition' => 'Pleasant or attractive.', 'example' => 'It is nice to meet you today.', 'level' => 'A1', 'part_of_speech' => 'adjective'],
            ['word' => 'paper', 'definition' => 'Material used for writing.', 'example' => 'He wrote the note on a piece of paper.', 'level' => 'A1', 'part_of_speech' => 'noun'],
            ['word' => 'rain', 'definition' => 'Water falling from the sky.', 'example' => 'The heavy rain stopped after an hour.', 'level' => 'A1', 'part_of_speech' => 'noun'],
            ['word' => 'road', 'definition' => 'A route for vehicles and people.', 'example' => 'They walked along the quiet country road.', 'level' => 'A1', 'part_of_speech' => 'noun'],
            ['word' => 'shoe', 'definition' => 'A covering for the foot.', 'example' => 'He tied his shoe before running.', 'level' => 'A1', 'part_of_speech' => 'noun'],
            ['word' => 'song', 'definition' => 'A short piece of music with words.', 'example' => 'She sang a beautiful song at school.', 'level' => 'A1', 'part_of_speech' => 'noun'],
            ['word' => 'star', 'definition' => 'A tiny bright point in the night sky.', 'example' => 'She looked at the brightest star in the sky.', 'level' => 'A1', 'part_of_speech' => 'noun'],
            ['word' => 'tree', 'definition' => 'A tall plant with a trunk.', 'example' => 'An old oak tree grows near their house.', 'level' => 'A1', 'part_of_speech' => 'noun'],
            ['word' => 'wind', 'definition' => 'A natural movement of the air.', 'example' => 'The cold wind blew the leaves away.', 'level' => 'A1', 'part_of_speech' => 'noun'],
            ['word' => 'year', 'definition' => 'A period of 365 days.', 'example' => 'We travel to the beach once a year.', 'level' => 'A1', 'part_of_speech' => 'noun'],
            ['word' => 'angry', 'definition' => 'Feeling strong displeasure.', 'example' => 'He was angry about the flight delay.', 'level' => 'A2', 'part_of_speech' => 'adjective'],
            ['word' => 'beach', 'definition' => 'Sandy shore by the ocean.', 'example' => 'They spent the day at the sandy beach.', 'level' => 'A2', 'part_of_speech' => 'noun'],
            ['word' => 'bread', 'definition' => 'Baked food made of flour and water.', 'example' => 'She bought a fresh loaf of bread.', 'level' => 'A2', 'part_of_speech' => 'noun'],
            ['word' => 'camel', 'definition' => 'A large animal with humps.', 'example' => 'The camel walked slowly across the desert.', 'level' => 'A2', 'part_of_speech' => 'noun'],
            ['word' => 'candy', 'definition' => 'Sweet food made with sugar.', 'example' => 'The child bought some colorful candy.', 'level' => 'A2', 'part_of_speech' => 'noun'],
            ['word' => 'cheap', 'definition' => 'Low in price or cost.', 'example' => 'The tickets were surprisingly cheap.', 'level' => 'A2', 'part_of_speech' => 'adjective'],
            ['word' => 'clean', 'definition' => 'Free from dirt or marks.', 'example' => 'Please keep your room tidy and clean.', 'level' => 'A2', 'part_of_speech' => 'adjective'],
            ['word' => 'cloud', 'definition' => 'A white mass in the sky.', 'example' => 'A white cloud covered the warm sun.', 'level' => 'A2', 'part_of_speech' => 'noun'],
            ['word' => 'count', 'definition' => 'To determine the number of items.', 'example' => 'He can count from one to ten.', 'level' => 'A2', 'part_of_speech' => 'verb'],
            ['word' => 'cry', 'definition' => 'To shed tears due to sadness.', 'example' => 'The sad movie made her cry a lot.', 'level' => 'A2', 'part_of_speech' => 'verb'],
            ['word' => 'dance', 'definition' => 'To move to music.', 'example' => 'They love to dance at parties.', 'level' => 'A2', 'part_of_speech' => 'verb'],
            ['word' => 'dirty', 'definition' => 'Not clean or covered in mud.', 'example' => 'He washed his dirty hands with soap.', 'level' => 'A2', 'part_of_speech' => 'adjective'],
            ['word' => 'dream', 'definition' => 'Thoughts occurring during sleep.', 'example' => 'She had a strange dream last night.', 'level' => 'A2', 'part_of_speech' => 'noun'],
            ['word' => 'dress', 'definition' => 'A one-piece garment for females.', 'example' => 'She wore a yellow dress to the dinner.', 'level' => 'A2', 'part_of_speech' => 'noun'],
            ['word' => 'early', 'definition' => 'Before the usual or expected time.', 'example' => 'He arrived early for the meeting.', 'level' => 'A2', 'part_of_speech' => 'adjective'],
            ['word' => 'earth', 'definition' => 'The planet on which we live.', 'example' => 'The earth rotates around the sun.', 'level' => 'A2', 'part_of_speech' => 'noun'],
            ['word' => 'enjoy', 'definition' => 'To take pleasure in something.', 'example' => 'They enjoy listening to classical music.', 'level' => 'A2', 'part_of_speech' => 'verb'],
            ['word' => 'fight', 'definition' => 'To engage in battle or physical struggle.', 'example' => 'The two brothers always fight over toys.', 'level' => 'A2', 'part_of_speech' => 'verb'],
            ['word' => 'fruit', 'definition' => 'Sweet product of a plant.', 'example' => 'Fresh fruit is part of a healthy diet.', 'level' => 'A2', 'part_of_speech' => 'noun'],
            ['word' => 'glass', 'definition' => 'A hard, transparent material.', 'example' => 'She filled the glass with orange juice.', 'level' => 'A2', 'part_of_speech' => 'noun'],
            ['word' => 'grass', 'definition' => 'Green vegetation in lawns.', 'example' => 'We sat on the green grass in the park.', 'level' => 'A2', 'part_of_speech' => 'noun'],
            ['word' => 'green', 'definition' => 'A color like grass.', 'example' => 'The leaves turn green in spring.', 'level' => 'A2', 'part_of_speech' => 'adjective'],
            ['word' => 'heart', 'definition' => 'The organ that pumps blood.', 'example' => 'His heart beat fast after running.', 'level' => 'A2', 'part_of_speech' => 'noun'],
            ['word' => 'heavy', 'definition' => 'Having great weight.', 'example' => 'This heavy box is difficult to lift.', 'level' => 'A2', 'part_of_speech' => 'adjective'],
            ['word' => 'horse', 'definition' => 'A large animal used for riding.', 'example' => 'He rode a beautiful white horse.', 'level' => 'A2', 'part_of_speech' => 'noun'],
            ['word' => 'knife', 'definition' => 'A tool used for cutting.', 'example' => 'Use a sharp knife to cut the bread.', 'level' => 'A2', 'part_of_speech' => 'noun'],
            ['word' => 'laugh', 'definition' => 'To make sounds of amusement.', 'example' => 'The funny joke made everyone laugh.', 'level' => 'A2', 'part_of_speech' => 'verb'],
            ['word' => 'light', 'definition' => 'The natural agent that stimulates sight.', 'example' => 'The bright light hurt his eyes.', 'level' => 'A2', 'part_of_speech' => 'noun'],
            ['word' => 'lunch', 'definition' => 'A meal eaten in the middle of the day.', 'example' => 'We had a quick lunch at the cafe.', 'level' => 'A2', 'part_of_speech' => 'noun'],
            ['word' => 'month', 'definition' => 'One of the twelve periods of a year.', 'example' => 'She will start her new job next month.', 'level' => 'A2', 'part_of_speech' => 'noun'],
            ['word' => 'neck', 'definition' => 'Part of body connecting head and shoulders.', 'example' => 'She wore a silver scarf around her neck.', 'level' => 'A2', 'part_of_speech' => 'noun'],
            ['word' => 'onion', 'definition' => 'A round vegetable with a strong smell.', 'example' => 'He chopped an onion for the soup.', 'level' => 'A2', 'part_of_speech' => 'noun'],
            ['word' => 'park', 'definition' => 'A public green area.', 'example' => 'They walked their dog in the park.', 'level' => 'A2', 'part_of_speech' => 'noun'],
            ['word' => 'plant', 'definition' => 'A living thing that grows in earth.', 'example' => 'She watered the plant on the balcony.', 'level' => 'A2', 'part_of_speech' => 'noun'],
            ['word' => 'plate', 'definition' => 'A flat dish for food.', 'example' => 'He put the cake on a small plate.', 'level' => 'A2', 'part_of_speech' => 'noun'],
            ['word' => 'pocket', 'definition' => 'A small pouch in clothing.', 'example' => 'He put his keys in his pocket.', 'level' => 'A2', 'part_of_speech' => 'noun'],
            ['word' => 'quick', 'definition' => 'Moving or doing something fast.', 'example' => 'They made a quick decision to leave.', 'level' => 'A2', 'part_of_speech' => 'adjective'],
            ['word' => 'quiet', 'definition' => 'Making very little noise.', 'example' => 'The library is a very quiet place.', 'level' => 'A2', 'part_of_speech' => 'adjective'],
            ['word' => 'river', 'definition' => 'A large natural stream of water.', 'example' => 'They caught fish in the deep river.', 'level' => 'A2', 'part_of_speech' => 'noun'],
            ['word' => 'salt', 'definition' => 'White substance used to flavor food.', 'example' => 'Add a pinch of salt to the sauce.', 'level' => 'A2', 'part_of_speech' => 'noun'],
            ['word' => 'sleep', 'definition' => 'A natural state of rest.', 'example' => 'You need eight hours of sleep daily.', 'level' => 'A2', 'part_of_speech' => 'verb'],
            ['word' => 'slow', 'definition' => 'Not moving or acting quickly.', 'example' => 'The train was very slow today.', 'level' => 'A2', 'part_of_speech' => 'adjective'],
            ['word' => 'small', 'definition' => 'Little in size or amount.', 'example' => 'They live in a small apartment.', 'level' => 'A2', 'part_of_speech' => 'adjective'],
            ['word' => 'smoke', 'definition' => 'Cloud produced by burning.', 'example' => 'Grey smoke rose from the chimney.', 'level' => 'A2', 'part_of_speech' => 'noun'],
            ['word' => 'snow', 'definition' => 'Frozen rain falling in flakes.', 'example' => 'White snow covered the streets.', 'level' => 'A2', 'part_of_speech' => 'noun'],
            ['word' => 'spoon', 'definition' => 'A tool used for eating soup.', 'example' => 'She stirred her coffee with a spoon.', 'level' => 'A2', 'part_of_speech' => 'noun'],
            ['word' => 'sport', 'definition' => 'A physical activity or game.', 'example' => 'Tennis is her favorite sport.', 'level' => 'A2', 'part_of_speech' => 'noun'],
            ['word' => 'stone', 'definition' => 'A small piece of rock.', 'example' => 'He threw a small stone into the pond.', 'level' => 'A2', 'part_of_speech' => 'noun'],
            ['word' => 'train', 'definition' => 'A series of connected railway carriages.', 'example' => 'We caught the train at nine o\'clock.', 'level' => 'A2', 'part_of_speech' => 'noun'],
            ['word' => 'valley', 'definition' => 'Low area of land between hills.', 'example' => 'The small village lies in a green valley.', 'level' => 'A2', 'part_of_speech' => 'noun'],
            ['word' => 'accent', 'definition' => 'A distinctive way of pronouncing a language.', 'example' => 'He speaks English with a strong French accent.', 'level' => 'B1', 'part_of_speech' => 'noun'],
            ['word' => 'active', 'definition' => 'Engaging or ready to engage in physically energetic pursuits.', 'example' => 'Despite her age, she is still very active.', 'level' => 'B1', 'part_of_speech' => 'adjective'],
            ['word' => 'advice', 'definition' => 'Guidance or recommendations offered.', 'example' => 'He asked his teacher for advice on studying.', 'level' => 'B1', 'part_of_speech' => 'noun'],
            ['word' => 'afraid', 'definition' => 'Feeling fear or anxiety.', 'example' => 'She is afraid of spiders and dark rooms.', 'level' => 'B1', 'part_of_speech' => 'adjective'],
            ['word' => 'agency', 'definition' => 'A business representing others.', 'example' => 'They booked their trip through a travel agency.', 'level' => 'B1', 'part_of_speech' => 'noun'],
            ['word' => 'amount', 'definition' => 'A quantity of something.', 'example' => 'We spent a large amount of time planning.', 'level' => 'B1', 'part_of_speech' => 'noun'],
            ['word' => 'border', 'definition' => 'The boundary between two countries.', 'example' => 'They crossed the border into Spain.', 'level' => 'B1', 'part_of_speech' => 'noun'],
            ['word' => 'brain', 'definition' => 'The organ of thought inside the head.', 'example' => 'Reading exercises the human brain.', 'level' => 'B1', 'part_of_speech' => 'noun'],
            ['word' => 'breeze', 'definition' => 'A gentle and pleasant wind.', 'example' => 'A cool breeze blew from the sea.', 'level' => 'B1', 'part_of_speech' => 'noun'],
            ['word' => 'bridge', 'definition' => 'A structure built over a river.', 'example' => 'The bridge connects the two sides of the city.', 'level' => 'B1', 'part_of_speech' => 'noun'],
            ['word' => 'camera', 'definition' => 'A device for taking photographs.', 'example' => 'He bought a high-quality digital camera.', 'level' => 'B1', 'part_of_speech' => 'noun'],
            ['word' => 'candle', 'definition' => 'A cylinder of wax with a central wick.', 'example' => 'She lit a scented candle in the living room.', 'level' => 'B1', 'part_of_speech' => 'noun'],
            ['word' => 'career', 'definition' => 'A profession followed for a significant period.', 'example' => 'He built a successful career in education.', 'level' => 'B1', 'part_of_speech' => 'noun'],
            ['word' => 'castle', 'definition' => 'A large fortified building.', 'example' => 'An ancient stone castle stood on the hill.', 'level' => 'B1', 'part_of_speech' => 'noun'],
            ['word' => 'chance', 'definition' => 'A possibility of something happening.', 'example' => 'There is a good chance it will rain tonight.', 'level' => 'B1', 'part_of_speech' => 'noun'],
            ['word' => 'choice', 'definition' => 'An act of choosing between options.', 'example' => 'You have a choice between coffee or tea.', 'level' => 'B1', 'part_of_speech' => 'noun'],
            ['word' => 'clever', 'definition' => 'Quick to understand or learn.', 'example' => 'The clever student solved the puzzle quickly.', 'level' => 'B1', 'part_of_speech' => 'adjective'],
            ['word' => 'corner', 'definition' => 'The place where two streets meet.', 'example' => 'The bakery is on the corner of the street.', 'level' => 'B1', 'part_of_speech' => 'noun'],
            ['word' => 'cousin', 'definition' => 'A child of one\'s uncle or aunt.', 'example' => 'I invited my favorite cousin to the dinner.', 'level' => 'B1', 'part_of_speech' => 'noun'],
            ['word' => 'danger', 'definition' => 'The possibility of suffering harm.', 'example' => 'There is danger in driving on icy roads.', 'level' => 'B1', 'part_of_speech' => 'noun'],
            ['word' => 'degree', 'definition' => 'An academic qualification.', 'example' => 'She earned a degree in computer science.', 'level' => 'B1', 'part_of_speech' => 'noun'],
            ['word' => 'desert', 'definition' => 'A dry, sandy area of land.', 'example' => 'Very few plants grow in the hot desert.', 'level' => 'B1', 'part_of_speech' => 'noun'],
            ['word' => 'detail', 'definition' => 'An individual fact or item.', 'example' => 'Please describe the plan in detail.', 'level' => 'B1', 'part_of_speech' => 'noun'],
            ['word' => 'dinner', 'definition' => 'The main meal of the day, eaten in the evening.', 'example' => 'They invited us to dinner at their house.', 'level' => 'B1', 'part_of_speech' => 'noun'],
            ['word' => 'double', 'definition' => 'Consisting of two equal things.', 'example' => 'They booked a room with a double bed.', 'level' => 'B1', 'part_of_speech' => 'adjective'],
            ['word' => 'driver', 'definition' => 'A person who operates a vehicle.', 'example' => 'The bus driver was polite and helpful.', 'level' => 'B1', 'part_of_speech' => 'noun'],
            ['word' => 'empty', 'definition' => 'Containing nothing or vacant.', 'example' => 'The box was completely empty inside.', 'level' => 'B1', 'part_of_speech' => 'adjective'],
            ['word' => 'engine', 'definition' => 'A machine that converts power into motion.', 'example' => 'The car engine stopped working in the cold.', 'level' => 'B1', 'part_of_speech' => 'noun'],
            ['word' => 'escape', 'definition' => 'To get free from danger.', 'example' => 'The prisoners tried to escape at night.', 'level' => 'B1', 'part_of_speech' => 'verb'],
            ['word' => 'event', 'definition' => 'A planned public or social occasion.', 'example' => 'The charity concert was a successful event.', 'level' => 'B1', 'part_of_speech' => 'noun'],
            ['word' => 'expert', 'definition' => 'A person with special knowledge.', 'example' => 'She is a leading expert in marine biology.', 'level' => 'B1', 'part_of_speech' => 'noun'],
            ['word' => 'factor', 'definition' => 'An influence that contributes to a result.', 'example' => 'Time was the main factor in our failure.', 'level' => 'B1', 'part_of_speech' => 'noun'],
            ['word' => 'flight', 'definition' => 'A journey made through the air.', 'example' => 'Their flight to Lisbon was delayed by fog.', 'level' => 'B1', 'part_of_speech' => 'noun'],
            ['word' => 'forest', 'definition' => 'A large area covered with trees.', 'example' => 'We went hiking in the deep forest.', 'level' => 'B1', 'part_of_speech' => 'noun'],
            ['word' => 'future', 'definition' => 'A period of time following the present.', 'example' => 'No one can predict the absolute future.', 'level' => 'B1', 'part_of_speech' => 'noun'],
            ['word' => 'garden', 'definition' => 'A piece of ground next to a house for growing plants.', 'example' => 'She planted red roses in her garden.', 'level' => 'B1', 'part_of_speech' => 'noun'],
            ['word' => 'growth', 'definition' => 'The process of increasing in size.', 'example' => 'The company recorded strong economic growth.', 'level' => 'B1', 'part_of_speech' => 'noun'],
            ['word' => 'height', 'definition' => 'The measurement from base to top.', 'example' => 'He measured the height of the door frame.', 'level' => 'B1', 'part_of_speech' => 'noun'],
            ['word' => 'hidden', 'definition' => 'Kept out of sight or concealed.', 'example' => 'They found a hidden path in the woods.', 'level' => 'B1', 'part_of_speech' => 'adjective'],
            ['word' => 'hungry', 'definition' => 'Feeling a need for food.', 'example' => 'The kids were very hungry after swimming.', 'level' => 'B1', 'part_of_speech' => 'adjective'],
            ['word' => 'insect', 'definition' => 'A small creature with six legs.', 'example' => 'A colorful insect landed on the leaf.', 'level' => 'B1', 'part_of_speech' => 'noun'],
            ['word' => 'island', 'definition' => 'A piece of land surrounded by water.', 'example' => 'They sailed to a beautiful tropical island.', 'level' => 'B1', 'part_of_speech' => 'noun'],
            ['word' => 'market', 'definition' => 'A regular gathering for buying and selling.', 'example' => 'We bought fresh vegetables at the local market.', 'level' => 'B1', 'part_of_speech' => 'noun'],
            ['word' => 'nature', 'definition' => 'The phenomena of the physical world.', 'example' => 'He enjoys spending quiet time in nature.', 'level' => 'B1', 'part_of_speech' => 'noun'],
            ['word' => 'option', 'definition' => 'A thing that is or may be chosen.', 'example' => 'Giving up is not a viable option.', 'level' => 'B1', 'part_of_speech' => 'noun'],
            ['word' => 'parent', 'definition' => 'A father or mother.', 'example' => 'Every parent wants the best for their child.', 'level' => 'B1', 'part_of_speech' => 'noun'],
            ['word' => 'pencil', 'definition' => 'An instrument for writing or drawing.', 'example' => 'He sketched the portrait with a pencil.', 'level' => 'B1', 'part_of_speech' => 'noun'],
            ['word' => 'reason', 'definition' => 'A cause or explanation for an event.', 'example' => 'Give me one good reason to believe you.', 'level' => 'B1', 'part_of_speech' => 'noun'],
            ['word' => 'shadow', 'definition' => 'A dark area produced by blocking light.', 'example' => 'The tree cast a long shadow on the lawn.', 'level' => 'B1', 'part_of_speech' => 'noun'],
            ['word' => 'sudden', 'definition' => 'Occurring or done quickly and unexpectedly.', 'example' => 'A sudden noise startled the sleeping baby.', 'level' => 'B1', 'part_of_speech' => 'adjective'],
            ['word' => 'acquire', 'definition' => 'To buy or obtain an asset.', 'example' => 'She worked hard to acquire new skills.', 'level' => 'B2', 'part_of_speech' => 'verb'],
            ['word' => 'adjust', 'definition' => 'To alter slightly to achieve fit.', 'example' => 'He had to adjust the seat to drive comfortably.', 'level' => 'B2', 'part_of_speech' => 'verb'],
            ['word' => 'analyze', 'definition' => 'To examine methodically.', 'example' => 'We need to analyze the laboratory results.', 'level' => 'B2', 'part_of_speech' => 'verb'],
            ['word' => 'annual', 'definition' => 'Occurring once every year.', 'example' => 'The annual report is published in January.', 'level' => 'B2', 'part_of_speech' => 'adjective'],
            ['word' => 'asset', 'definition' => 'A useful or valuable quality or thing.', 'example' => 'Fluency in English is a major asset in business.', 'level' => 'B2', 'part_of_speech' => 'noun'],
            ['word' => 'capture', 'definition' => 'To record or express accurately.', 'example' => 'The photo managed to capture her beautiful smile.', 'level' => 'B2', 'part_of_speech' => 'verb'],
            ['word' => 'catalog', 'definition' => 'A complete list of items in systematic order.', 'example' => 'He searched the library catalog for the book.', 'level' => 'B2', 'part_of_speech' => 'noun'],
            ['word' => 'citizen', 'definition' => 'A legally recognized subject of a state.', 'example' => 'He is a proud citizen of Portugal.', 'level' => 'B2', 'part_of_speech' => 'noun'],
            ['word' => 'classic', 'definition' => 'Judged over time to be of the highest quality.', 'example' => 'He bought a classic black leather jacket.', 'level' => 'B2', 'part_of_speech' => 'adjective'],
            ['word' => 'climate', 'definition' => 'The weather conditions prevailing in an area.', 'example' => 'The region is known for its mild climate.', 'level' => 'B2', 'part_of_speech' => 'noun'],
            ['word' => 'closure', 'definition' => 'A feeling of resolution or conclusion.', 'example' => 'The apology gave her a sense of final closure.', 'level' => 'B2', 'part_of_speech' => 'noun'],
            ['word' => 'cluster', 'definition' => 'A group of similar things positioned closely.', 'example' => 'A small cluster of stars appeared in the night sky.', 'level' => 'B2', 'part_of_speech' => 'noun'],
            ['word' => 'collect', 'definition' => 'To bring things together.', 'example' => 'They collect rare coins from around the world.', 'level' => 'B2', 'part_of_speech' => 'verb'],
            ['word' => 'columns', 'definition' => 'Vertical divisions of a page or text.', 'example' => 'The newspaper layout has three neat columns.', 'level' => 'B2', 'part_of_speech' => 'noun'],
            ['word' => 'combat', 'definition' => 'To take action to reduce or prevent.', 'example' => 'New measures were introduced to combat drug crime.', 'level' => 'B2', 'part_of_speech' => 'verb'],
            ['word' => 'command', 'definition' => 'An authoritative directive or order.', 'example' => 'The soldiers obeyed the captain\'s firm command.', 'level' => 'B2', 'part_of_speech' => 'noun'],
            ['word' => 'complex', 'definition' => 'Consisting of many different and connected parts.', 'example' => 'The puzzle had a very complex design.', 'level' => 'B2', 'part_of_speech' => 'adjective'],
            ['word' => 'conduct', 'definition' => 'To organize and carry out an activity.', 'example' => 'We need to conduct a thorough research survey.', 'level' => 'B2', 'part_of_speech' => 'verb'],
            ['word' => 'consent', 'definition' => 'Permission for something to happen.', 'example' => 'No operations are performed without patient consent.', 'level' => 'B2', 'part_of_speech' => 'noun'],
            ['word' => 'context', 'definition' => 'The circumstances that form the setting for an event.', 'example' => 'You must look at the quote in context.', 'level' => 'B2', 'part_of_speech' => 'noun'],
            ['word' => 'crucial', 'definition' => 'Of great importance or decisive.', 'example' => 'Good coordination is crucial for the team\'s victory.', 'level' => 'B2', 'part_of_speech' => 'adjective'],
            ['word' => 'current', 'definition' => 'Belonging to the present time.', 'example' => 'What is your current physical address?', 'level' => 'B2', 'part_of_speech' => 'adjective'],
            ['word' => 'custom', 'definition' => 'A traditional way of behaving.', 'example' => 'It is a local custom to exchange gifts.', 'level' => 'B2', 'part_of_speech' => 'noun'],
            ['word' => 'decade', 'definition' => 'A period of ten years.', 'example' => 'The technology has changed rapidly over the decade.', 'level' => 'B2', 'part_of_speech' => 'noun'],
            ['word' => 'decline', 'definition' => 'To become smaller, fewer, or less.', 'example' => 'The demand for coal continues to decline.', 'level' => 'B2', 'part_of_speech' => 'verb'],
            ['word' => 'defend', 'definition' => 'To protect from harm or danger.', 'example' => 'The soldiers fought bravely to defend the fortress.', 'level' => 'B2', 'part_of_speech' => 'verb'],
            ['word' => 'defense', 'definition' => 'Action taken to protect against attack.', 'example' => 'A strong defense is essential in football.', 'level' => 'B2', 'part_of_speech' => 'noun'],
            ['word' => 'deficit', 'definition' => 'An excess of expenditure over income.', 'example' => 'The national budget deficit rose this fiscal year.', 'level' => 'B2', 'part_of_speech' => 'noun'],
            ['word' => 'density', 'definition' => 'The degree of compactness of a substance.', 'example' => 'The population density in Tokyo is extremely high.', 'level' => 'B2', 'part_of_speech' => 'noun'],
            ['word' => 'deposit', 'definition' => 'A sum of money paid into a bank account.', 'example' => 'He made a cash deposit of one hundred dollars.', 'level' => 'B2', 'part_of_speech' => 'noun'],
            ['word' => 'derive', 'definition' => 'To obtain something from a specific source.', 'example' => 'Many English words derive from ancient Latin.', 'level' => 'B2', 'part_of_speech' => 'verb'],
            ['word' => 'dessert', 'definition' => 'Sweet food eaten at the end of a meal.', 'example' => 'We ordered apple pie for our dessert.', 'level' => 'B2', 'part_of_speech' => 'noun'],
            ['word' => 'detect', 'definition' => 'To discover or identify the presence of.', 'example' => 'The radar can detect small aircraft.', 'level' => 'B2', 'part_of_speech' => 'verb'],
            ['word' => 'device', 'definition' => 'An instrument made for a particular purpose.', 'example' => 'This handheld device is highly practical.', 'level' => 'B2', 'part_of_speech' => 'noun'],
            ['word' => 'diary', 'definition' => 'A book in which one keeps a daily record.', 'example' => 'She kept a personal diary during her travels.', 'level' => 'B2', 'part_of_speech' => 'noun'],
            ['word' => 'digital', 'definition' => 'Expressed in numerical digits, especially binary.', 'example' => 'We live in an increasingly digital world.', 'level' => 'B2', 'part_of_speech' => 'adjective'],
            ['word' => 'dilemma', 'definition' => 'A difficult situation or choice.', 'example' => 'Having two job offers was an pleasant dilemma.', 'level' => 'B2', 'part_of_speech' => 'noun'],
            ['word' => 'dismiss', 'definition' => 'To decide that something is not important.', 'example' => 'Do not dismiss the idea without trying it.', 'level' => 'B2', 'part_of_speech' => 'verb'],
            ['word' => 'display', 'definition' => 'To show or exhibit publicly.', 'example' => 'The museum will display the ancient relics.', 'level' => 'B2', 'part_of_speech' => 'verb'],
            ['word' => 'diverse', 'definition' => 'Showing a great deal of variety.', 'example' => 'The university attracts a highly diverse student group.', 'level' => 'B2', 'part_of_speech' => 'adjective'],
            ['word' => 'dynamic', 'definition' => 'Characterized by constant change or progress.', 'example' => 'Market forces demand dynamic corporate strategies.', 'level' => 'B2', 'part_of_speech' => 'adjective'],
            ['word' => 'edition', 'definition' => 'A particular version of a published text.', 'example' => 'She bought the latest edition of the dictionary.', 'level' => 'B2', 'part_of_speech' => 'noun'],
            ['word' => 'elastic', 'definition' => 'Able to resume normal shape after stretching.', 'example' => 'The waist of these trousers is fully elastic.', 'level' => 'B2', 'part_of_speech' => 'adjective'],
            ['word' => 'element', 'definition' => 'An essential part of something.', 'example' => 'Trust is a key element of any friendship.', 'level' => 'B2', 'part_of_speech' => 'noun'],
            ['word' => 'elegant', 'definition' => 'Graceful and stylish in appearance.', 'example' => 'She wore an elegant black gown.', 'level' => 'B2', 'part_of_speech' => 'adjective'],
            ['word' => 'emerald', 'definition' => 'A bright green precious stone.', 'example' => 'Her necklace featured a large shining emerald.', 'level' => 'B2', 'part_of_speech' => 'noun'],
            ['word' => 'emerge', 'definition' => 'To become apparent or prominent.', 'example' => 'New details emerge as the inquiry proceeds.', 'level' => 'B2', 'part_of_speech' => 'verb'],
            ['word' => 'emotion', 'definition' => 'A strong feeling such as joy.', 'example' => 'His voice trembled with strong emotion.', 'level' => 'B2', 'part_of_speech' => 'noun'],
            ['word' => 'empire', 'definition' => 'A large group of states ruled by a single monarch.', 'example' => 'He read a book on the ancient Roman Empire.', 'level' => 'B2', 'part_of_speech' => 'noun'],
            ['word' => 'faculty', 'definition' => 'An inherent mental or physical power.', 'example' => 'He retained his mental faculty until a late age.', 'level' => 'B2', 'part_of_speech' => 'noun'],
            ['word' => 'abstract', 'definition' => 'Existing in thought but not having physical existence.', 'example' => 'Truth and beauty are highly abstract concepts.', 'level' => 'C1', 'part_of_speech' => 'adjective'],
            ['word' => 'acoustic', 'definition' => 'Relating to sound or hearing.', 'example' => 'The hall is known for its excellent acoustic design.', 'level' => 'C1', 'part_of_speech' => 'adjective'],
            ['word' => 'acute', 'definition' => 'Severe or intense in a high degree.', 'example' => 'There is an acute shortage of clean water.', 'level' => 'C1', 'part_of_speech' => 'adjective'],
            ['word' => 'adjacent', 'definition' => 'Next to or adjoining something else.', 'example' => 'Their house is adjacent to the green park.', 'level' => 'C1', 'part_of_speech' => 'adjective'],
            ['word' => 'advocate', 'definition' => 'A person who publicly supports a cause.', 'example' => 'She is a passionate advocate for child education.', 'level' => 'C1', 'part_of_speech' => 'noun'],
            ['word' => 'alliance', 'definition' => 'A union or association formed for mutual benefit.', 'example' => 'The two countries formed a defensive alliance.', 'level' => 'C1', 'part_of_speech' => 'noun'],
            ['word' => 'alloy', 'definition' => 'A metal made by combining two or more metallic elements.', 'example' => 'Brass is an alloy of copper and zinc.', 'level' => 'C1', 'part_of_speech' => 'noun'],
            ['word' => 'amateur', 'definition' => 'A person who engages in a pursuit on an unpaid basis.', 'example' => 'The play was performed by a talented amateur group.', 'level' => 'C1', 'part_of_speech' => 'noun'],
            ['word' => 'analogy', 'definition' => 'A comparison between one thing and another.', 'example' => 'The teacher used a simple analogy to explain gravity.', 'level' => 'C1', 'part_of_speech' => 'noun'],
            ['word' => 'analyst', 'definition' => 'A person who conducts methodical analysis.', 'example' => 'He works as a financial analyst at a large bank.', 'level' => 'C1', 'part_of_speech' => 'noun'],
            ['word' => 'ancestor', 'definition' => 'A person from whom one is descended.', 'example' => 'Her ancestor arrived in this country a century ago.', 'level' => 'C1', 'part_of_speech' => 'noun'],
            ['word' => 'anomaly', 'definition' => 'Something that deviates from what is standard.', 'example' => 'The high temperature in winter was an anomaly.', 'level' => 'C1', 'part_of_speech' => 'noun'],
            ['word' => 'approval', 'definition' => 'The belief that someone or something is good.', 'example' => 'The project received the board\'s official approval.', 'level' => 'C1', 'part_of_speech' => 'noun'],
            ['word' => 'arbitrary', 'definition' => 'Based on random choice rather than reason.', 'example' => 'The rules seemed completely arbitrary and unfair.', 'level' => 'C1', 'part_of_speech' => 'adjective'],
            ['word' => 'archive', 'definition' => 'A collection of historical documents.', 'example' => 'The ancient treaties are kept in the state archive.', 'level' => 'C1', 'part_of_speech' => 'noun'],
            ['word' => 'aroma', 'definition' => 'A pleasant and distinctive smell.', 'example' => 'The delicious aroma of fresh coffee filled the kitchen.', 'level' => 'C1', 'part_of_speech' => 'noun'],
            ['word' => 'artifact', 'definition' => 'An object made by a human being of historical interest.', 'example' => 'They discovered a rare gold artifact in the cave.', 'level' => 'C1', 'part_of_speech' => 'noun'],
            ['word' => 'boundary', 'definition' => 'A line that marks the limit of an area.', 'example' => 'The river forms a natural boundary between counties.', 'level' => 'C1', 'part_of_speech' => 'noun'],
            ['word' => 'breach', 'definition' => 'An act of breaking a law or agreement.', 'example' => 'Selling the data was a clear breach of contract.', 'level' => 'C1', 'part_of_speech' => 'noun'],
            ['word' => 'brilliant', 'definition' => 'Exceptionally clever or talented.', 'example' => 'The young scientist proposed a brilliant solution.', 'level' => 'C1', 'part_of_speech' => 'adjective'],
            ['word' => 'browse', 'definition' => 'To survey goods or information casually.', 'example' => 'I love to browse in old bookstores on weekends.', 'level' => 'C1', 'part_of_speech' => 'verb'],
            ['word' => 'calendar', 'definition' => 'A chart showing the days and months.', 'example' => 'Mark the date of the exam on your calendar.', 'level' => 'C1', 'part_of_speech' => 'noun'],
            ['word' => 'capsule', 'definition' => 'A small gelatinous case enclosing medicine.', 'example' => 'She took a vitamin capsule after her breakfast.', 'level' => 'C1', 'part_of_speech' => 'noun'],
            ['word' => 'casual', 'definition' => 'Relaxed and unconcerned.', 'example' => 'His casual attitude towards studies was worrying.', 'level' => 'C1', 'part_of_speech' => 'adjective'],
            ['word' => 'catalyst', 'definition' => 'An event or person that causes change.', 'example' => 'The new law was a catalyst for economic growth.', 'level' => 'C1', 'part_of_speech' => 'noun'],
            ['word' => 'caution', 'definition' => 'Care taken to avoid danger or mistakes.', 'example' => 'Drive with extreme caution in heavy rain.', 'level' => 'C1', 'part_of_speech' => 'noun'],
            ['word' => 'cavity', 'definition' => 'An empty space within a solid object.', 'example' => 'The dentist filled a deep cavity in his tooth.', 'level' => 'C1', 'part_of_speech' => 'noun'],
            ['word' => 'ceramic', 'definition' => 'Clay baked at high temperatures.', 'example' => 'She bought a beautiful handmade ceramic vase.', 'level' => 'C1', 'part_of_speech' => 'noun'],
            ['word' => 'chaotic', 'definition' => 'In a state of complete confusion.', 'example' => 'The traffic was chaotic after the power outage.', 'level' => 'C1', 'part_of_speech' => 'adjective'],
            ['word' => 'chronic', 'definition' => 'Persisting for a long time.', 'example' => 'He suffers from a painful chronic back illness.', 'level' => 'C1', 'part_of_speech' => 'adjective'],
            ['word' => 'circuit', 'definition' => 'A complete path for electrical current.', 'example' => 'A broken wire caused a short circuit.', 'level' => 'C1', 'part_of_speech' => 'noun'],
            ['word' => 'citation', 'definition' => 'A reference to a scholarly source.', 'example' => 'The essay lacked even a single academic citation.', 'level' => 'C1', 'part_of_speech' => 'noun'],
            ['word' => 'clarify', 'definition' => 'To make a statement less confusing.', 'example' => 'The manager called a meeting to clarify the policy.', 'level' => 'C1', 'part_of_speech' => 'verb'],
            ['word' => 'cognitive', 'definition' => 'Relating to intellectual activity.', 'example' => 'Puzzles help maintain healthy cognitive skills.', 'level' => 'C1', 'part_of_speech' => 'adjective'],
            ['word' => 'compact', 'definition' => 'Closely and neatly packed together.', 'example' => 'They bought a small compact car for city driving.', 'level' => 'C1', 'part_of_speech' => 'adjective'],
            ['word' => 'compile', 'definition' => 'To assemble information from various sources.', 'example' => 'We need to compile a comprehensive database.', 'level' => 'C1', 'part_of_speech' => 'verb'],
            ['word' => 'comprise', 'definition' => 'To consist of or be made up of.', 'example' => 'The committee will comprise ten senior members.', 'level' => 'C1', 'part_of_speech' => 'verb'],
            ['word' => 'concede', 'definition' => 'To admit that something is true after denying it.', 'example' => 'The candidate refused to concede the close election.', 'level' => 'C1', 'part_of_speech' => 'verb'],
            ['word' => 'concrete', 'definition' => 'Existing in a material or physical form.', 'example' => 'We need concrete evidence before making arrests.', 'level' => 'C1', 'part_of_speech' => 'adjective'],
            ['word' => 'condone', 'definition' => 'To accept and allow bad behavior.', 'example' => 'The school does not condone violence of any kind.', 'level' => 'C1', 'part_of_speech' => 'verb'],
            ['word' => 'conduit', 'definition' => 'A channel for conveying fluid or cables.', 'example' => 'The cables are protected inside a metal conduit.', 'level' => 'C1', 'part_of_speech' => 'noun'],
            ['word' => 'confine', 'definition' => 'To keep or restrict within limits.', 'example' => 'Please confine your comments to the agenda topic.', 'level' => 'C1', 'part_of_speech' => 'verb'],
            ['word' => 'conflict', 'definition' => 'A serious disagreement or argument.', 'example' => 'The two countries are in a bitter border conflict.', 'level' => 'C1', 'part_of_speech' => 'noun'],
            ['word' => 'conform', 'definition' => 'To comply with rules or standards.', 'example' => 'All products must conform to safety regulations.', 'level' => 'C1', 'part_of_speech' => 'verb'],
            ['word' => 'confront', 'definition' => 'To face up to and deal with a problem.', 'example' => 'We must confront these severe challenges directly.', 'level' => 'C1', 'part_of_speech' => 'verb'],
            ['word' => 'convey', 'definition' => 'To communicate a message or transport something.', 'example' => 'Please convey my warm regards to your parents.', 'level' => 'C1', 'part_of_speech' => 'verb'],
            ['word' => 'conserve', 'definition' => 'To protect something from harm or decay.', 'example' => 'We need to conserve water during dry summers.', 'level' => 'C1', 'part_of_speech' => 'verb'],
            ['word' => 'consist', 'definition' => 'To be composed or made up of.', 'example' => 'Healthy diets consist of vegetables and grains.', 'level' => 'C1', 'part_of_speech' => 'verb'],
            ['word' => 'consoles', 'definition' => 'Devices used for playing video games.', 'example' => 'Modern gaming consoles offer high-definition graphics.', 'level' => 'C1', 'part_of_speech' => 'noun'],
            ['word' => 'conspire', 'definition' => 'To make secret plans jointly to commit a crime.', 'example' => 'They conspired to steal the famous painting.', 'level' => 'C1', 'part_of_speech' => 'verb'],
            ['word' => 'absolute', 'definition' => 'Complete and unconditional.', 'example' => 'The monarch ruled with absolute power.', 'level' => 'C2', 'part_of_speech' => 'adjective'],
            ['word' => 'abyss', 'definition' => 'A deep or seemingly bottomless chasm.', 'example' => 'The climber stared down into the dark abyss.', 'level' => 'C2', 'part_of_speech' => 'noun'],
            ['word' => 'acumen', 'definition' => 'The ability to make good judgments.', 'example' => 'His business acumen led the startup to success.', 'level' => 'C2', 'part_of_speech' => 'noun'],
            ['word' => 'adverse', 'definition' => 'Preventing success or development.', 'example' => 'The flight was cancelled due to adverse weather.', 'level' => 'C2', 'part_of_speech' => 'adjective'],
            ['word' => 'adhere', 'definition' => 'To stick to a surface or follow a rule strictly.', 'example' => 'All members must adhere to the club\'s regulations.', 'level' => 'C2', 'part_of_speech' => 'verb'],
            ['word' => 'affinity', 'definition' => 'A natural liking or sympathy for someone.', 'example' => 'She has a special affinity for classical art.', 'level' => 'C2', 'part_of_speech' => 'noun'],
            ['word' => 'agile', 'definition' => 'Able to move quickly and easily.', 'example' => 'The agile gymnast performed a perfect flip.', 'level' => 'C2', 'part_of_speech' => 'adjective'],
            ['word' => 'alchemy', 'definition' => 'A seemingly magical process of transformation.', 'example' => 'The chef\'s skill was a form of culinary alchemy.', 'level' => 'C2', 'part_of_speech' => 'noun'],
            ['word' => 'alias', 'definition' => 'A false identity used by a criminal.', 'example' => 'The spy traveled under a clever alias.', 'level' => 'C2', 'part_of_speech' => 'noun'],
            ['word' => 'allude', 'definition' => 'To suggest or call attention to indirectly.', 'example' => 'The speaker did not allude to the scandal.', 'level' => 'C2', 'part_of_speech' => 'verb'],
            ['word' => 'aloof', 'definition' => 'Not friendly or willing to take part.', 'example' => 'He stood aloof from the arguing crowd.', 'level' => 'C2', 'part_of_speech' => 'adjective'],
            ['word' => 'altitude', 'definition' => 'The height of an object above sea level.', 'example' => 'The plane flew at a high altitude.', 'level' => 'C2', 'part_of_speech' => 'noun'],
            ['word' => 'altruism', 'definition' => 'Disinterested and selfless concern for others.', 'example' => 'Her charity work was an act of pure altruism.', 'level' => 'C2', 'part_of_speech' => 'noun'],
            ['word' => 'ambient', 'definition' => 'Relating to the immediate surroundings.', 'example' => 'We enjoyed the warm ambient light of the room.', 'level' => 'C2', 'part_of_speech' => 'adjective'],
            ['word' => 'amenity', 'definition' => 'A desirable or useful feature of a place.', 'example' => 'The luxury hotel offered every modern amenity.', 'level' => 'C2', 'part_of_speech' => 'noun'],
            ['word' => 'amity', 'definition' => 'A friendly relationship.', 'example' => 'The treaty was signed in a spirit of amity.', 'level' => 'C2', 'part_of_speech' => 'noun'],
            ['word' => 'amnesty', 'definition' => 'An official pardon for political offenses.', 'example' => 'The government declared amnesty for all rebels.', 'level' => 'C2', 'part_of_speech' => 'noun'],
            ['word' => 'anarchy', 'definition' => 'A state of disorder due to absence of authority.', 'example' => 'The collapse of the police led to total anarchy.', 'level' => 'C2', 'part_of_speech' => 'noun'],
            ['word' => 'anatomy', 'definition' => 'The bodily structure of humans.', 'example' => 'Doctors study human anatomy for many years.', 'level' => 'C2', 'part_of_speech' => 'noun'],
            ['word' => 'anchor', 'definition' => 'A heavy metal device used to secure a ship.', 'example' => 'They dropped the anchor in the quiet bay.', 'level' => 'C2', 'part_of_speech' => 'noun'],
            ['word' => 'angular', 'definition' => 'Having sharp corners or angles.', 'example' => 'The modern building featured a bold angular design.', 'level' => 'C2', 'part_of_speech' => 'adjective'],
            ['word' => 'antidote', 'definition' => 'A medicine taken to counteract a poison.', 'example' => 'Doctors searched for a rapid antidote to the venom.', 'level' => 'C2', 'part_of_speech' => 'noun'],
            ['word' => 'apex', 'definition' => 'The highest point of something.', 'example' => 'The eagle built its nest at the mountain apex.', 'level' => 'C2', 'part_of_speech' => 'noun'],
            ['word' => 'apathy', 'definition' => 'A lack of interest or enthusiasm.', 'example' => 'Widespread student apathy concerned the principal.', 'level' => 'C2', 'part_of_speech' => 'noun'],
            ['word' => 'applaud', 'definition' => 'To show strong approval publicly.', 'example' => 'We applaud the government\'s brave decision.', 'level' => 'C2', 'part_of_speech' => 'verb'],
            ['word' => 'archaic', 'definition' => 'Very old or old-fashioned.', 'example' => 'The school abandoned its archaic dress code rules.', 'level' => 'C2', 'part_of_speech' => 'adjective'],
            ['word' => 'arena', 'definition' => 'A place for sports or public events.', 'example' => 'Thousands of fans gathered in the sports arena.', 'level' => 'C2', 'part_of_speech' => 'noun'],
            ['word' => 'artisan', 'definition' => 'A worker skilled in a skilled trade.', 'example' => 'The artisan crafted beautiful wooden furniture.', 'level' => 'C2', 'part_of_speech' => 'noun'],
            ['word' => 'ascend', 'definition' => 'To go or climb up.', 'example' => 'They watched the hot air balloon ascend slowly.', 'level' => 'C2', 'part_of_speech' => 'verb'],
            ['word' => 'ascent', 'definition' => 'An instance of rising or climbing up.', 'example' => 'The mountain ascent took five exhausting hours.', 'level' => 'C2', 'part_of_speech' => 'noun'],
            ['word' => 'aspire', 'definition' => 'To direct one\'s hopes towards achieving.', 'example' => 'Young athletes aspire to win Olympic medals.', 'level' => 'C2', 'part_of_speech' => 'verb'],
            ['word' => 'assert', 'definition' => 'To state a fact confidently and forcefully.', 'example' => 'The lawyer continued to assert her client\'s innocence.', 'level' => 'C2', 'part_of_speech' => 'verb'],
            ['word' => 'asthma', 'definition' => 'A condition marked by breathing difficulty.', 'example' => 'Cold weather can trigger a painful asthma attack.', 'level' => 'C2', 'part_of_speech' => 'noun'],
            ['word' => 'asylum', 'definition' => 'Protection granted by a nation to refugees.', 'example' => 'They fled the war and requested political asylum.', 'level' => 'C2', 'part_of_speech' => 'noun'],
            ['word' => 'atlas', 'definition' => 'A book of maps or charts.', 'example' => 'He opened the old atlas to locate the island.', 'level' => 'C2', 'part_of_speech' => 'noun'],
            ['word' => 'atom', 'definition' => 'The basic unit of a chemical element.', 'example' => 'A water molecule has two hydrogen atoms.', 'level' => 'C2', 'part_of_speech' => 'noun'],
            ['word' => 'audit', 'definition' => 'An official inspection of accounts.', 'example' => 'The tax department ordered an official audit.', 'level' => 'C2', 'part_of_speech' => 'noun'],
            ['word' => 'aura', 'definition' => 'A distinctive atmosphere surrounding a person.', 'example' => 'The old library has a quiet, majestic aura.', 'level' => 'C2', 'part_of_speech' => 'noun'],
            ['word' => 'aurora', 'definition' => 'A natural light display in the polar sky.', 'example' => 'They traveled north to photograph the aurora.', 'level' => 'C2', 'part_of_speech' => 'noun'],
            ['word' => 'austere', 'definition' => 'Severe or strict in manner or appearance.', 'example' => 'The monk lived a quiet, austere life in the hills.', 'level' => 'C2', 'part_of_speech' => 'adjective'],
            ['word' => 'authentic', 'definition' => 'Of undisputed origin or genuine.', 'example' => 'They served authentic Italian pizza at the dinner.', 'level' => 'C2', 'part_of_speech' => 'adjective'],
            ['word' => 'autonomy', 'definition' => 'The right of self-government.', 'example' => 'The region requested greater political autonomy.', 'level' => 'C2', 'part_of_speech' => 'noun'],
            ['word' => 'avalanche', 'definition' => 'A mass of snow sliding down a mountain.', 'example' => 'The skiers escaped a dangerous snow avalanche.', 'level' => 'C2', 'part_of_speech' => 'noun'],
            ['word' => 'axiom', 'definition' => 'A statement accepted as established truth.', 'example' => 'The geometric proof was based on a simple axiom.', 'level' => 'C2', 'part_of_speech' => 'noun'],
            ['word' => 'axis', 'definition' => 'An imaginary line about which a body rotates.', 'example' => 'The earth rotates on its tilted axis daily.', 'level' => 'C2', 'part_of_speech' => 'noun'],
            ['word' => 'azure', 'definition' => 'Bright blue in color like a cloudless sky.', 'example' => 'The warm ocean water was a brilliant azure.', 'level' => 'C2', 'part_of_speech' => 'adjective'],
            ['word' => 'backup', 'definition' => 'A copy of files to protect against loss.', 'example' => 'Always keep a secure backup of your files.', 'level' => 'C2', 'part_of_speech' => 'noun'],
            ['word' => 'baffle', 'definition' => 'To totally confuse or perplex.', 'example' => 'The complex puzzle managed to baffle the expert.', 'level' => 'C2', 'part_of_speech' => 'verb'],
            ['word' => 'banish', 'definition' => 'To send someone away as official punishment.', 'example' => 'The king decided to banish the rebel leader.', 'level' => 'C2', 'part_of_speech' => 'verb'],
            ['word' => 'barren', 'definition' => 'Land too poor to produce vegetation.', 'example' => 'They crossed the dry, barren mountain landscape.', 'level' => 'C2', 'part_of_speech' => 'adjective'],
        ])->map(fn (array $word): array => [
            ...$word,
            'created_at' => $now,
            'updated_at' => $now,
        ])->all();

        Word::upsert(
            $words,
            ['word'],
            ['definition', 'example', 'level', 'part_of_speech', 'updated_at']
        );
    }
}
