export type Level = "A1" | "A2" | "B1" | "B2" | "C1" | "C2";

export type PracticeMode = "auto" | "level" | "review" | "seen";

export type VocabWord = {
  id: number;
  word: string;
  definition: string;
  definition_pt?: string;
  example: string;
  example_with_blank: string;
  level: Level;
  part_of_speech?: string | null;
};

export type WordProgress = {
  attempts: number;
  correctAttempts: number;
  incorrectAttempts: number;
  streakCorrect: number;
  intervalDays: number;
  easeFactor: number;
  learned: boolean;
  lastAnsweredAt: string | null;
  nextReviewAt: string | null;
};

export type HistoryItem = {
  id: string;
  word: string;
  level: Level;
  answer: string;
  correct: boolean;
  score: number;
  mode: PracticeMode;
  studiedAt: string;
};

export type StudyState = {
  clientId: string;
  wordProgress: Record<string, WordProgress>;
  history: HistoryItem[];
  xp: number;
  level: number;
  currentStreak: number;
  bestStreak: number;
  lastStudyDate: string | null;
  totalAttempts: number;
  correctAttempts: number;
};

type RawWord = [string, string, string, Level, string];

export const levels: Level[] = ["A1", "A2", "B1", "B2", "C1", "C2"];

export const modeLabels: Record<PracticeMode, string> = {
  auto: "Progressao",
  level: "Nivel",
  review: "Revisao",
  seen: "Ja vistas",
};

const rawWords: RawWord[] = [
  ["apple", "A round fruit with red, green, or yellow skin.", "She packed an apple for lunch.", "A1", "noun"],
  ["book", "A set of written pages that you read.", "He opened the book before class.", "A1", "noun"],
  ["city", "A large town where many people live and work.", "The city is busy in the morning.", "A1", "noun"],
  ["family", "A group of people related to each other.", "My family eats dinner together.", "A1", "noun"],
  ["friend", "A person you like and know well.", "Her friend helped with the homework.", "A1", "noun"],
  ["happy", "Feeling good or pleased.", "The children were happy at the party.", "A1", "adjective"],
  ["listen", "To give attention to a sound or speaker.", "Please listen to the question carefully.", "A1", "verb"],
  ["morning", "The early part of the day.", "I drink water every morning.", "A1", "noun"],
  ["school", "A place where students learn.", "They walk to school at eight.", "A1", "noun"],
  ["water", "A clear liquid that people drink.", "She drinks water after running.", "A1", "noun"],
  ["chair", "A seat for one person.", "The chair is next to the window.", "A1", "noun"],
  ["door", "A thing you open to enter or leave a room.", "Please close the door quietly.", "A1", "noun"],
  ["food", "Things people or animals eat.", "The food smells good today.", "A1", "noun"],
  ["house", "A building where people live.", "Their house has a small garden.", "A1", "noun"],
  ["mother", "A female parent.", "My mother works at the hospital.", "A1", "noun"],
  ["music", "Sounds made by voices or instruments.", "We listen to music after dinner.", "A1", "noun"],
  ["phone", "A device used to call or message people.", "His phone is on the table.", "A1", "noun"],
  ["picture", "An image, drawing, or photograph.", "She took a picture of the beach.", "A1", "noun"],
  ["table", "A piece of furniture with a flat top.", "Put the keys on the table.", "A1", "noun"],
  ["work", "A job or activity that needs effort.", "He goes to work by bus.", "A1", "noun"],
  ["borrow", "To use something and give it back later.", "Can I borrow your pen for a minute?", "A2", "verb"],
  ["careful", "Taking time to avoid mistakes or danger.", "Be careful when you cross the street.", "A2", "adjective"],
  ["decide", "To choose after thinking about options.", "We need to decide where to eat.", "A2", "verb"],
  ["explain", "To make something clear or easy to understand.", "The teacher will explain the rule again.", "A2", "verb"],
  ["healthy", "Good for your body or not sick.", "A healthy breakfast gives you energy.", "A2", "adjective"],
  ["improve", "To become better or make something better.", "Daily practice can improve your English.", "A2", "verb"],
  ["mistake", "Something that is not correct.", "I made a mistake in the last sentence.", "A2", "noun"],
  ["simple", "Easy to understand or do.", "The instructions are simple and clear.", "A2", "adjective"],
  ["travel", "To go from one place to another.", "They travel by train on weekends.", "A2", "verb"],
  ["weather", "The temperature, wind, rain, or sun outside.", "The weather is colder today.", "A2", "noun"],
  ["arrive", "To reach a place.", "The train will arrive before noon.", "A2", "verb"],
  ["choose", "To pick one thing from several options.", "You can choose a topic for homework.", "A2", "verb"],
  ["describe", "To say what something or someone is like.", "Can you describe your new apartment?", "A2", "verb"],
  ["favorite", "Liked more than others.", "Blue is her favorite color.", "A2", "adjective"],
  ["invite", "To ask someone to come to an event.", "They will invite us to the party.", "A2", "verb"],
  ["journey", "A trip from one place to another.", "The journey took three hours by car.", "A2", "noun"],
  ["noisy", "Making a lot of sound.", "The noisy street made it hard to sleep.", "A2", "adjective"],
  ["protect", "To keep someone or something safe.", "A coat can protect you from the rain.", "A2", "verb"],
  ["repair", "To fix something that is broken.", "He will repair the bike this weekend.", "A2", "verb"],
  ["useful", "Helpful or practical.", "This map is useful in a new city.", "A2", "adjective"],
  ["achieve", "To succeed in doing something after effort.", "She worked hard to achieve her goal.", "B1", "verb"],
  ["benefit", "A good effect or advantage.", "One benefit of reading is a larger vocabulary.", "B1", "noun"],
  ["confident", "Feeling sure about your ability.", "He felt confident before the interview.", "B1", "adjective"],
  ["manage", "To control or organize something successfully.", "They manage the project with a small team.", "B1", "verb"],
  ["opinion", "What someone thinks or believes about something.", "In my opinion, the plan is realistic.", "B1", "noun"],
  ["prevent", "To stop something from happening.", "A helmet can prevent serious injury.", "B1", "verb"],
  ["reduce", "To make something smaller or less.", "We should reduce the amount of waste.", "B1", "verb"],
  ["reliable", "Able to be trusted or depended on.", "This is a reliable source of information.", "B1", "adjective"],
  ["struggle", "To have difficulty doing something.", "Many students struggle with pronunciation.", "B1", "verb"],
  ["support", "To help someone or agree with an idea.", "Her parents support her decision.", "B1", "verb"],
  ["approach", "A way of doing or thinking about something.", "Her approach to study is very organized.", "B1", "noun"],
  ["balance", "A state where different things have the right amount.", "Good balance helps you study and rest.", "B1", "noun"],
  ["compare", "To look at two things and see similarities or differences.", "Compare the answers before you choose.", "B1", "verb"],
  ["develop", "To grow or become more advanced.", "You can develop confidence through practice.", "B1", "verb"],
  ["encourage", "To give someone hope or confidence.", "Teachers encourage students to speak more.", "B1", "verb"],
  ["focus", "To give attention to one thing.", "Focus on the words you often forget.", "B1", "verb"],
  ["involve", "To include someone or something.", "The task will involve reading and speaking.", "B1", "verb"],
  ["likely", "Expected to happen or be true.", "A short review is likely to help.", "B1", "adjective"],
  ["recognize", "To know someone or something from before.", "I recognize this word from yesterday.", "B1", "verb"],
  ["suggest", "To offer an idea or plan.", "I suggest a shorter practice session.", "B1", "verb"],
  ["accomplish", "To complete something successfully.", "The team hopes to accomplish the task today.", "B2", "verb"],
  ["challenge", "A difficult task that tests ability.", "Learning ten new words a day is a challenge.", "B2", "noun"],
  ["consequence", "A result of an action or situation.", "The consequence of missing practice was clear.", "B2", "noun"],
  ["estimate", "To guess an amount based on available information.", "We estimate the lesson will take twenty minutes.", "B2", "verb"],
  ["evidence", "Facts or signs that show something is true.", "The report provides evidence for the claim.", "B2", "noun"],
  ["maintain", "To keep something at the same level or condition.", "You need regular practice to maintain fluency.", "B2", "verb"],
  ["negotiate", "To discuss in order to reach an agreement.", "They negotiate the price before signing.", "B2", "verb"],
  ["prioritize", "To decide what is most important.", "Students should prioritize the words they often miss.", "B2", "verb"],
  ["remarkable", "Unusual or impressive in a way people notice.", "Her progress this month was remarkable.", "B2", "adjective"],
  ["sustainable", "Able to continue for a long time without harm.", "A sustainable study routine is better than cramming.", "B2", "adjective"],
  ["accurate", "Correct and without mistakes.", "An accurate answer earns more points.", "B2", "adjective"],
  ["adapt", "To change in order to fit a new situation.", "Good learners adapt their routine over time.", "B2", "verb"],
  ["convince", "To make someone believe or agree.", "The data can convince them to continue.", "B2", "verb"],
  ["evaluate", "To judge the value or quality of something.", "Evaluate your mistakes after each round.", "B2", "verb"],
  ["framework", "A basic structure for ideas or work.", "The framework helps organize the lesson.", "B2", "noun"],
  ["generate", "To produce or create something.", "The app can generate a new challenge.", "B2", "verb"],
  ["insight", "A clear understanding of something.", "The feedback gave her insight into grammar.", "B2", "noun"],
  ["objective", "A goal or purpose.", "The objective is to remember words faster.", "B2", "noun"],
  ["resolve", "To solve a problem or difficulty.", "They resolve confusion by checking examples.", "B2", "verb"],
  ["tension", "A feeling of stress or pressure.", "Time limits add tension to the game.", "B2", "noun"],
  ["ambiguous", "Having more than one possible meaning.", "The ambiguous sentence confused the class.", "C1", "adjective"],
  ["coherent", "Clear, logical, and easy to understand.", "Her argument was coherent and persuasive.", "C1", "adjective"],
  ["compelling", "Very interesting or convincing.", "The speaker gave a compelling reason to continue.", "C1", "adjective"],
  ["concise", "Using few words while staying clear.", "A concise answer is often more effective.", "C1", "adjective"],
  ["deteriorate", "To become worse over time.", "Without practice, pronunciation can deteriorate.", "C1", "verb"],
  ["implement", "To put a plan or system into action.", "The school will implement a new study plan.", "C1", "verb"],
  ["leverage", "To use something effectively to get a result.", "You can leverage daily habits to learn faster.", "C1", "verb"],
  ["mitigate", "To make a problem less serious.", "Short reviews can mitigate forgetting.", "C1", "verb"],
  ["resilient", "Able to recover quickly after difficulty.", "A resilient learner keeps going after mistakes.", "C1", "adjective"],
  ["substantial", "Large in amount, value, or importance.", "She made substantial progress in six weeks.", "C1", "adjective"],
  ["allocate", "To decide how resources or time should be used.", "Allocate ten minutes to review difficult words.", "C1", "verb"],
  ["articulate", "To express an idea clearly.", "She can articulate complex ideas in English.", "C1", "verb"],
  ["constraint", "A limit or restriction.", "A time constraint can sharpen your focus.", "C1", "noun"],
  ["cultivate", "To develop a skill or habit carefully.", "Cultivate curiosity when you meet new words.", "C1", "verb"],
  ["diminish", "To become or make something smaller.", "Regular review can diminish repeated mistakes.", "C1", "verb"],
  ["formulate", "To create or prepare something carefully.", "Formulate a sentence before you answer.", "C1", "verb"],
  ["inherent", "Existing as a natural part of something.", "There is inherent uncertainty in translation.", "C1", "adjective"],
  ["pragmatic", "Focused on practical results.", "A pragmatic plan fits your real schedule.", "C1", "adjective"],
  ["refine", "To improve something by making small changes.", "Refine your answer after reading the clue.", "C1", "verb"],
  ["scrutiny", "Careful and detailed examination.", "Every example sentence received scrutiny.", "C1", "noun"],
  ["ephemeral", "Lasting for only a short time.", "Motivation can be ephemeral without a clear routine.", "C2", "adjective"],
  ["exacerbate", "To make a bad situation worse.", "Skipping review can exacerbate memory gaps.", "C2", "verb"],
  ["incongruous", "Strange because it does not fit with its surroundings.", "The formal phrase felt incongruous in casual speech.", "C2", "adjective"],
  ["meticulous", "Very careful and attentive to detail.", "A meticulous learner checks each pronunciation.", "C2", "adjective"],
  ["nuance", "A small but important difference in meaning.", "The nuance between the two verbs is subtle.", "C2", "noun"],
  ["paradigm", "A typical model or way of thinking about something.", "Spaced repetition changed the paradigm of memorization.", "C2", "noun"],
  ["proliferation", "A rapid increase in the number of something.", "The proliferation of apps gives learners many choices.", "C2", "noun"],
  ["scrutinize", "To examine something very carefully.", "Advanced students scrutinize word choice in essays.", "C2", "verb"],
  ["ubiquitous", "Present or found everywhere.", "English words are ubiquitous in technology.", "C2", "adjective"],
  ["unequivocal", "Clear and leaving no doubt.", "The feedback was unequivocal after the wrong answer.", "C2", "adjective"],
  ["aberration", "Something unusual that differs from what is normal.", "One low score was an aberration in her record.", "C2", "noun"],
  ["conflate", "To combine two ideas as if they were the same.", "Writers sometimes conflate similar concepts.", "C2", "verb"],
  ["dissonance", "A lack of agreement or harmony.", "The phrase created dissonance in the paragraph.", "C2", "noun"],
  ["intractable", "Very difficult to control or solve.", "The intractable error required deeper analysis.", "C2", "adjective"],
  ["labyrinthine", "Complicated and confusing like a maze.", "The labyrinthine explanation lost the audience.", "C2", "adjective"],
  ["obfuscate", "To make something unclear or hard to understand.", "Do not obfuscate a simple argument.", "C2", "verb"],
  ["perfunctory", "Done quickly and without real care.", "A perfunctory review rarely fixes weak vocabulary.", "C2", "adjective"],
  ["quintessential", "Representing the most typical example.", "That sentence is a quintessential formal opening.", "C2", "adjective"],
  ["tacit", "Understood without being directly said.", "The tacit rule was clear from context.", "C2", "adjective"],
  ["vindicate", "To prove that someone or something was right.", "The final score can vindicate steady practice.", "C2", "verb"],
  ["baby", "A very young child.", "The baby is sleeping in the crib.", "A1", "noun"],
  ["ball", "A round object used in games.", "He kicked the ball into the net.", "A1", "noun"],
  ["bank", "A place where people keep money.", "She goes to the bank to save money.", "A1", "noun"],
  ["bath", "An act of washing the body.", "He takes a hot bath every evening.", "A1", "noun"],
  ["beer", "An alcoholic drink made from grain.", "He ordered a cold beer at the bar.", "A1", "noun"],
  ["bird", "An animal with feathers and wings.", "A small bird sang on the tree branch.", "A1", "noun"],
  ["blue", "A color like the clear sky.", "She wore a beautiful blue dress.", "A1", "adjective"],
  ["boat", "A small vehicle for traveling on water.", "They rented a small boat on the lake.", "A1", "noun"],
  ["body", "The physical structure of a person.", "Exercise is good for your body.", "A1", "noun"],
  ["busy", "Having a lot of things to do.", "The doctor is very busy today.", "A1", "adjective"],
  ["cake", "A sweet baked food.", "She made a chocolate cake for his birthday.", "A1", "noun"],
  ["card", "A small piece of stiff paper.", "He wrote a birthday card for his mom.", "A1", "noun"],
  ["cat", "A small domesticated animal.", "The cat is sleeping on the sofa.", "A1", "noun"],
  ["cold", "Having a low temperature.", "The water is too cold to swim in.", "A1", "adjective"],
  ["coat", "An outer piece of clothing.", "Put on your coat before going outside.", "A1", "noun"],
  ["cup", "A small container used for drinking.", "She drank a cup of hot tea.", "A1", "noun"],
  ["dark", "With little or no light.", "The street was dark at midnight.", "A1", "adjective"],
  ["date", "A specific day of the month.", "What is the date today?", "A1", "noun"],
  ["day", "A period of twenty-four hours.", "It is a beautiful day today.", "A1", "noun"],
  ["dog", "A common animal kept as a pet.", "The dog barked at the stranger.", "A1", "noun"],
  ["draw", "To make a picture with a pen.", "Children love to draw pictures of animals.", "A1", "verb"],
  ["drink", "To take liquid into the mouth.", "Please drink some water.", "A1", "verb"],
  ["easy", "Not difficult to do.", "The exam was very easy.", "A1", "adjective"],
  ["egg", "An oval object produced by a bird.", "She fried an egg for breakfast.", "A1", "noun"],
  ["eye", "The organ of sight.", "She closed her eye during the movie.", "A1", "noun"],
  ["face", "The front part of the head.", "She washed her face with warm water.", "A1", "noun"],
  ["fire", "Heat and light from burning.", "They sat close to the warm fire.", "A1", "noun"],
  ["fish", "An animal that lives in water.", "We saw many fish in the river.", "A1", "noun"],
  ["game", "An activity played for fun.", "They played a fun game after dinner.", "A1", "noun"],
  ["girl", "A female child.", "The little girl wore a red hat.", "A1", "noun"],
  ["hair", "The fine threads on the head.", "She has long brown hair.", "A1", "noun"],
  ["hand", "The part of the arm below the wrist.", "He held the cup with his left hand.", "A1", "noun"],
  ["head", "The upper part of the body.", "Wear a helmet to protect your head.", "A1", "noun"],
  ["hot", "Having a high temperature.", "The soup is very hot today.", "A1", "adjective"],
  ["kind", "Friendly and generous.", "She was very kind to the tourist.", "A1", "adjective"],
  ["land", "The solid part of the earth.", "The plane landed safely on dry land.", "A1", "noun"],
  ["life", "The period of being alive.", "He wants to live a peaceful life.", "A1", "noun"],
  ["love", "A strong feeling of affection.", "They showed great love for their pets.", "A1", "noun"],
  ["milk", "A white liquid produced by cows.", "He drinks a glass of milk daily.", "A1", "noun"],
  ["name", "A word by which a person is known.", "Please write your name here.", "A1", "noun"],
  ["nice", "Pleasant or attractive.", "It is nice to meet you today.", "A1", "adjective"],
  ["paper", "Material used for writing.", "He wrote the note on a piece of paper.", "A1", "noun"],
  ["rain", "Water falling from the sky.", "The heavy rain stopped after an hour.", "A1", "noun"],
  ["road", "A route for vehicles and people.", "They walked along the quiet country road.", "A1", "noun"],
  ["shoe", "A covering for the foot.", "He tied his shoe before running.", "A1", "noun"],
  ["song", "A short piece of music with words.", "She sang a beautiful song at school.", "A1", "noun"],
  ["star", "A tiny bright point in the night sky.", "She looked at the brightest star in the sky.", "A1", "noun"],
  ["tree", "A tall plant with a trunk.", "An old oak tree grows near their house.", "A1", "noun"],
  ["wind", "A natural movement of the air.", "The cold wind blew the leaves away.", "A1", "noun"],
  ["year", "A period of 365 days.", "We travel to the beach once a year.", "A1", "noun"],
  ["angry", "Feeling strong displeasure.", "He was angry about the flight delay.", "A2", "adjective"],
  ["beach", "Sandy shore by the ocean.", "They spent the day at the sandy beach.", "A2", "noun"],
  ["bread", "Baked food made of flour and water.", "She bought a fresh loaf of bread.", "A2", "noun"],
  ["camel", "A large animal with humps.", "The camel walked slowly across the desert.", "A2", "noun"],
  ["candy", "Sweet food made with sugar.", "The child bought some colorful candy.", "A2", "noun"],
  ["cheap", "Low in price or cost.", "The tickets were surprisingly cheap.", "A2", "adjective"],
  ["clean", "Free from dirt or marks.", "Please keep your room tidy and clean.", "A2", "adjective"],
  ["cloud", "A white mass in the sky.", "A white cloud covered the warm sun.", "A2", "noun"],
  ["count", "To determine the number of items.", "He can count from one to ten.", "A2", "verb"],
  ["cry", "To shed tears due to sadness.", "The sad movie made her cry a lot.", "A2", "verb"],
  ["dance", "To move to music.", "They love to dance at parties.", "A2", "verb"],
  ["dirty", "Not clean or covered in mud.", "He washed his dirty hands with soap.", "A2", "adjective"],
  ["dream", "Thoughts occurring during sleep.", "She had a strange dream last night.", "A2", "noun"],
  ["dress", "A one-piece garment for females.", "She wore a yellow dress to the dinner.", "A2", "noun"],
  ["early", "Before the usual or expected time.", "He arrived early for the meeting.", "A2", "adjective"],
  ["earth", "The planet on which we live.", "The earth rotates around the sun.", "A2", "noun"],
  ["enjoy", "To take pleasure in something.", "They enjoy listening to classical music.", "A2", "verb"],
  ["fight", "To engage in battle or physical struggle.", "The two brothers always fight over toys.", "A2", "verb"],
  ["fruit", "Sweet product of a plant.", "Fresh fruit is part of a healthy diet.", "A2", "noun"],
  ["glass", "A hard, transparent material.", "She filled the glass with orange juice.", "A2", "noun"],
  ["grass", "Green vegetation in lawns.", "We sat on the green grass in the park.", "A2", "noun"],
  ["green", "A color like grass.", "The leaves turn green in spring.", "A2", "adjective"],
  ["heart", "The organ that pumps blood.", "His heart beat fast after running.", "A2", "noun"],
  ["heavy", "Having great weight.", "This heavy box is difficult to lift.", "A2", "adjective"],
  ["horse", "A large animal used for riding.", "He rode a beautiful white horse.", "A2", "noun"],
  ["knife", "A tool used for cutting.", "Use a sharp knife to cut the bread.", "A2", "noun"],
  ["laugh", "To make sounds of amusement.", "The funny joke made everyone laugh.", "A2", "verb"],
  ["light", "The natural agent that stimulates sight.", "The bright light hurt his eyes.", "A2", "noun"],
  ["lunch", "A meal eaten in the middle of the day.", "We had a quick lunch at the cafe.", "A2", "noun"],
  ["month", "One of the twelve periods of a year.", "She will start her new job next month.", "A2", "noun"],
  ["neck", "Part of body connecting head and shoulders.", "She wore a silver scarf around her neck.", "A2", "noun"],
  ["onion", "A round vegetable with a strong smell.", "He chopped an onion for the soup.", "A2", "noun"],
  ["park", "A public green area.", "They walked their dog in the park.", "A2", "noun"],
  ["plant", "A living thing that grows in earth.", "She watered the plant on the balcony.", "A2", "noun"],
  ["plate", "A flat dish for food.", "He put the cake on a small plate.", "A2", "noun"],
  ["pocket", "A small pouch in clothing.", "He put his keys in his pocket.", "A2", "noun"],
  ["quick", "Moving or doing something fast.", "They made a quick decision to leave.", "A2", "adjective"],
  ["quiet", "Making very little noise.", "The library is a very quiet place.", "A2", "adjective"],
  ["river", "A large natural stream of water.", "They caught fish in the deep river.", "A2", "noun"],
  ["salt", "White substance used to flavor food.", "Add a pinch of salt to the sauce.", "A2", "noun"],
  ["sleep", "A natural state of rest.", "You need eight hours of sleep daily.", "A2", "verb"],
  ["slow", "Not moving or acting quickly.", "The train was very slow today.", "A2", "adjective"],
  ["small", "Little in size or amount.", "They live in a small apartment.", "A2", "adjective"],
  ["smoke", "Cloud produced by burning.", "Grey smoke rose from the chimney.", "A2", "noun"],
  ["snow", "Frozen rain falling in flakes.", "White snow covered the streets.", "A2", "noun"],
  ["spoon", "A tool used for eating soup.", "She stirred her coffee with a spoon.", "A2", "noun"],
  ["sport", "A physical activity or game.", "Tennis is her favorite sport.", "A2", "noun"],
  ["stone", "A small piece of rock.", "He threw a small stone into the pond.", "A2", "noun"],
  ["train", "A series of connected railway carriages.", "We caught the train at nine o'clock.", "A2", "noun"],
  ["valley", "Low area of land between hills.", "The small village lies in a green valley.", "A2", "noun"],
  ["accent", "A distinctive way of pronouncing a language.", "He speaks English with a strong French accent.", "B1", "noun"],
  ["active", "Engaging or ready to engage in physically energetic pursuits.", "Despite her age, she is still very active.", "B1", "adjective"],
  ["advice", "Guidance or recommendations offered.", "He asked his teacher for advice on studying.", "B1", "noun"],
  ["afraid", "Feeling fear or anxiety.", "She is afraid of spiders and dark rooms.", "B1", "adjective"],
  ["agency", "A business representing others.", "They booked their trip through a travel agency.", "B1", "noun"],
  ["amount", "A quantity of something.", "We spent a large amount of time planning.", "B1", "noun"],
  ["border", "The boundary between two countries.", "They crossed the border into Spain.", "B1", "noun"],
  ["brain", "The organ of thought inside the head.", "Reading exercises the human brain.", "B1", "noun"],
  ["breeze", "A gentle and pleasant wind.", "A cool breeze blew from the sea.", "B1", "noun"],
  ["bridge", "A structure built over a river.", "The bridge connects the two sides of the city.", "B1", "noun"],
  ["camera", "A device for taking photographs.", "He bought a high-quality digital camera.", "B1", "noun"],
  ["candle", "A cylinder of wax with a central wick.", "She lit a scented candle in the living room.", "B1", "noun"],
  ["career", "A profession followed for a significant period.", "He built a successful career in education.", "B1", "noun"],
  ["castle", "A large fortified building.", "An ancient stone castle stood on the hill.", "B1", "noun"],
  ["chance", "A possibility of something happening.", "There is a good chance it will rain tonight.", "B1", "noun"],
  ["choice", "An act of choosing between options.", "You have a choice between coffee or tea.", "B1", "noun"],
  ["clever", "Quick to understand or learn.", "The clever student solved the puzzle quickly.", "B1", "adjective"],
  ["corner", "The place where two streets meet.", "The bakery is on the corner of the street.", "B1", "noun"],
  ["cousin", "A child of one's uncle or aunt.", "I invited my favorite cousin to the dinner.", "B1", "noun"],
  ["danger", "The possibility of suffering harm.", "There is danger in driving on icy roads.", "B1", "noun"],
  ["degree", "An academic qualification.", "She earned a degree in computer science.", "B1", "noun"],
  ["desert", "A dry, sandy area of land.", "Very few plants grow in the hot desert.", "B1", "noun"],
  ["detail", "An individual fact or item.", "Please describe the plan in detail.", "B1", "noun"],
  ["dinner", "The main meal of the day, eaten in the evening.", "They invited us to dinner at their house.", "B1", "noun"],
  ["double", "Consisting of two equal things.", "They booked a room with a double bed.", "B1", "adjective"],
  ["driver", "A person who operates a vehicle.", "The bus driver was polite and helpful.", "B1", "noun"],
  ["empty", "Containing nothing or vacant.", "The box was completely empty inside.", "B1", "adjective"],
  ["engine", "A machine that converts power into motion.", "The car engine stopped working in the cold.", "B1", "noun"],
  ["escape", "To get free from danger.", "The prisoners tried to escape at night.", "B1", "verb"],
  ["event", "A planned public or social occasion.", "The charity concert was a successful event.", "B1", "noun"],
  ["expert", "A person with special knowledge.", "She is a leading expert in marine biology.", "B1", "noun"],
  ["factor", "An influence that contributes to a result.", "Time was the main factor in our failure.", "B1", "noun"],
  ["flight", "A journey made through the air.", "Their flight to Lisbon was delayed by fog.", "B1", "noun"],
  ["forest", "A large area covered with trees.", "We went hiking in the deep forest.", "B1", "noun"],
  ["future", "A period of time following the present.", "No one can predict the absolute future.", "B1", "noun"],
  ["garden", "A piece of ground next to a house for growing plants.", "She planted red roses in her garden.", "B1", "noun"],
  ["growth", "The process of increasing in size.", "The company recorded strong economic growth.", "B1", "noun"],
  ["height", "The measurement from base to top.", "He measured the height of the door frame.", "B1", "noun"],
  ["hidden", "Kept out of sight or concealed.", "They found a hidden path in the woods.", "B1", "adjective"],
  ["hungry", "Feeling a need for food.", "The kids were very hungry after swimming.", "B1", "adjective"],
  ["insect", "A small creature with six legs.", "A colorful insect landed on the leaf.", "B1", "noun"],
  ["island", "A piece of land surrounded by water.", "They sailed to a beautiful tropical island.", "B1", "noun"],
  ["market", "A regular gathering for buying and selling.", "We bought fresh vegetables at the local market.", "B1", "noun"],
  ["nature", "The phenomena of the physical world.", "He enjoys spending quiet time in nature.", "B1", "noun"],
  ["option", "A thing that is or may be chosen.", "Giving up is not a viable option.", "B1", "noun"],
  ["parent", "A father or mother.", "Every parent wants the best for their child.", "B1", "noun"],
  ["pencil", "An instrument for writing or drawing.", "He sketched the portrait with a pencil.", "B1", "noun"],
  ["reason", "A cause or explanation for an event.", "Give me one good reason to believe you.", "B1", "noun"],
  ["shadow", "A dark area produced by blocking light.", "The tree cast a long shadow on the lawn.", "B1", "noun"],
  ["sudden", "Occurring or done quickly and unexpectedly.", "A sudden noise startled the sleeping baby.", "B1", "adjective"],
  ["acquire", "To buy or obtain an asset.", "She worked hard to acquire new skills.", "B2", "verb"],
  ["adjust", "To alter slightly to achieve fit.", "He had to adjust the seat to drive comfortably.", "B2", "verb"],
  ["analyze", "To examine methodically.", "We need to analyze the laboratory results.", "B2", "verb"],
  ["annual", "Occurring once every year.", "The annual report is published in January.", "B2", "adjective"],
  ["asset", "A useful or valuable quality or thing.", "Fluency in English is a major asset in business.", "B2", "noun"],
  ["capture", "To record or express accurately.", "The photo managed to capture her beautiful smile.", "B2", "verb"],
  ["catalog", "A complete list of items in systematic order.", "He searched the library catalog for the book.", "B2", "noun"],
  ["citizen", "A legally recognized subject of a state.", "He is a proud citizen of Portugal.", "B2", "noun"],
  ["classic", "Judged over time to be of the highest quality.", "He bought a classic black leather jacket.", "B2", "adjective"],
  ["climate", "The weather conditions prevailing in an area.", "The region is known for its mild climate.", "B2", "noun"],
  ["closure", "A feeling of resolution or conclusion.", "The apology gave her a sense of final closure.", "B2", "noun"],
  ["cluster", "A group of similar things positioned closely.", "A small cluster of stars appeared in the night sky.", "B2", "noun"],
  ["collect", "To bring things together.", "They collect rare coins from around the world.", "B2", "verb"],
  ["columns", "Vertical divisions of a page or text.", "The newspaper layout has three neat columns.", "B2", "noun"],
  ["combat", "To take action to reduce or prevent.", "New measures were introduced to combat drug crime.", "B2", "verb"],
  ["command", "An authoritative directive or order.", "The soldiers obeyed the captain's firm command.", "B2", "noun"],
  ["complex", "Consisting of many different and connected parts.", "The puzzle had a very complex design.", "B2", "adjective"],
  ["conduct", "To organize and carry out an activity.", "We need to conduct a thorough research survey.", "B2", "verb"],
  ["consent", "Permission for something to happen.", "No operations are performed without patient consent.", "B2", "noun"],
  ["context", "The circumstances that form the setting for an event.", "You must look at the quote in context.", "B2", "noun"],
  ["crucial", "Of great importance or decisive.", "Good coordination is crucial for the team's victory.", "B2", "adjective"],
  ["current", "Belonging to the present time.", "What is your current physical address?", "B2", "adjective"],
  ["custom", "A traditional way of behaving.", "It is a local custom to exchange gifts.", "B2", "noun"],
  ["decade", "A period of ten years.", "The technology has changed rapidly over the decade.", "B2", "noun"],
  ["decline", "To become smaller, fewer, or less.", "The demand for coal continues to decline.", "B2", "verb"],
  ["defend", "To protect from harm or danger.", "The soldiers fought bravely to defend the fortress.", "B2", "verb"],
  ["defense", "Action taken to protect against attack.", "A strong defense is essential in football.", "B2", "noun"],
  ["deficit", "An excess of expenditure over income.", "The national budget deficit rose this fiscal year.", "B2", "noun"],
  ["density", "The degree of compactness of a substance.", "The population density in Tokyo is extremely high.", "B2", "noun"],
  ["deposit", "A sum of money paid into a bank account.", "He made a cash deposit of one hundred dollars.", "B2", "noun"],
  ["derive", "To obtain something from a specific source.", "Many English words derive from ancient Latin.", "B2", "verb"],
  ["dessert", "Sweet food eaten at the end of a meal.", "We ordered apple pie for our dessert.", "B2", "noun"],
  ["detect", "To discover or identify the presence of.", "The radar can detect small aircraft.", "B2", "verb"],
  ["device", "An instrument made for a particular purpose.", "This handheld device is highly practical.", "B2", "noun"],
  ["diary", "A book in which one keeps a daily record.", "She kept a personal diary during her travels.", "B2", "noun"],
  ["digital", "Expressed in numerical digits, especially binary.", "We live in an increasingly digital world.", "B2", "adjective"],
  ["dilemma", "A difficult situation or choice.", "Having two job offers was an pleasant dilemma.", "B2", "noun"],
  ["dismiss", "To decide that something is not important.", "Do not dismiss the idea without trying it.", "B2", "verb"],
  ["display", "To show or exhibit publicly.", "The museum will display the ancient relics.", "B2", "verb"],
  ["diverse", "Showing a great deal of variety.", "The university attracts a highly diverse student group.", "B2", "adjective"],
  ["dynamic", "Characterized by constant change or progress.", "Market forces demand dynamic corporate strategies.", "B2", "adjective"],
  ["edition", "A particular version of a published text.", "She bought the latest edition of the dictionary.", "B2", "noun"],
  ["elastic", "Able to resume normal shape after stretching.", "The waist of these trousers is fully elastic.", "B2", "adjective"],
  ["element", "An essential part of something.", "Trust is a key element of any friendship.", "B2", "noun"],
  ["elegant", "Graceful and stylish in appearance.", "She wore an elegant black gown.", "B2", "adjective"],
  ["emerald", "A bright green precious stone.", "Her necklace featured a large shining emerald.", "B2", "noun"],
  ["emerge", "To become apparent or prominent.", "New details emerge as the inquiry proceeds.", "B2", "verb"],
  ["emotion", "A strong feeling such as joy.", "His voice trembled with strong emotion.", "B2", "noun"],
  ["empire", "A large group of states ruled by a single monarch.", "He read a book on the ancient Roman Empire.", "B2", "noun"],
  ["faculty", "An inherent mental or physical power.", "He retained his mental faculty until a late age.", "B2", "noun"],
  ["abstract", "Existing in thought but not having physical existence.", "Truth and beauty are highly abstract concepts.", "C1", "adjective"],
  ["acoustic", "Relating to sound or hearing.", "The hall is known for its excellent acoustic design.", "C1", "adjective"],
  ["acute", "Severe or intense in a high degree.", "There is an acute shortage of clean water.", "C1", "adjective"],
  ["adjacent", "Next to or adjoining something else.", "Their house is adjacent to the green park.", "C1", "adjective"],
  ["advocate", "A person who publicly supports a cause.", "She is a passionate advocate for child education.", "C1", "noun"],
  ["alliance", "A union or association formed for mutual benefit.", "The two countries formed a defensive alliance.", "C1", "noun"],
  ["alloy", "A metal made by combining two or more metallic elements.", "Brass is an alloy of copper and zinc.", "C1", "noun"],
  ["amateur", "A person who engages in a pursuit on an unpaid basis.", "The play was performed by a talented amateur group.", "C1", "noun"],
  ["analogy", "A comparison between one thing and another.", "The teacher used a simple analogy to explain gravity.", "C1", "noun"],
  ["analyst", "A person who conducts methodical analysis.", "He works as a financial analyst at a large bank.", "C1", "noun"],
  ["ancestor", "A person from whom one is descended.", "Her ancestor arrived in this country a century ago.", "C1", "noun"],
  ["anomaly", "Something that deviates from what is standard.", "The high temperature in winter was an anomaly.", "C1", "noun"],
  ["approval", "The belief that someone or something is good.", "The project received the board's official approval.", "C1", "noun"],
  ["arbitrary", "Based on random choice rather than reason.", "The rules seemed completely arbitrary and unfair.", "C1", "adjective"],
  ["archive", "A collection of historical documents.", "The ancient treaties are kept in the state archive.", "C1", "noun"],
  ["aroma", "A pleasant and distinctive smell.", "The delicious aroma of fresh coffee filled the kitchen.", "C1", "noun"],
  ["artifact", "An object made by a human being of historical interest.", "They discovered a rare gold artifact in the cave.", "C1", "noun"],
  ["boundary", "A line that marks the limit of an area.", "The river forms a natural boundary between counties.", "C1", "noun"],
  ["breach", "An act of breaking a law or agreement.", "Selling the data was a clear breach of contract.", "C1", "noun"],
  ["brilliant", "Exceptionally clever or talented.", "The young scientist proposed a brilliant solution.", "C1", "adjective"],
  ["browse", "To survey goods or information casually.", "I love to browse in old bookstores on weekends.", "C1", "verb"],
  ["calendar", "A chart showing the days and months.", "Mark the date of the exam on your calendar.", "C1", "noun"],
  ["capsule", "A small gelatinous case enclosing medicine.", "She took a vitamin capsule after her breakfast.", "C1", "noun"],
  ["casual", "Relaxed and unconcerned.", "His casual attitude towards studies was worrying.", "C1", "adjective"],
  ["catalyst", "An event or person that causes change.", "The new law was a catalyst for economic growth.", "C1", "noun"],
  ["caution", "Care taken to avoid danger or mistakes.", "Drive with extreme caution in heavy rain.", "C1", "noun"],
  ["cavity", "An empty space within a solid object.", "The dentist filled a deep cavity in his tooth.", "C1", "noun"],
  ["ceramic", "Clay baked at high temperatures.", "She bought a beautiful handmade ceramic vase.", "C1", "noun"],
  ["chaotic", "In a state of complete confusion.", "The traffic was chaotic after the power outage.", "C1", "adjective"],
  ["chronic", "Persisting for a long time.", "He suffers from a painful chronic back illness.", "C1", "adjective"],
  ["circuit", "A complete path for electrical current.", "A broken wire caused a short circuit.", "C1", "noun"],
  ["citation", "A reference to a scholarly source.", "The essay lacked even a single academic citation.", "C1", "noun"],
  ["clarify", "To make a statement less confusing.", "The manager called a meeting to clarify the policy.", "C1", "verb"],
  ["cognitive", "Relating to intellectual activity.", "Puzzles help maintain healthy cognitive skills.", "C1", "adjective"],
  ["compact", "Closely and neatly packed together.", "They bought a small compact car for city driving.", "C1", "adjective"],
  ["compile", "To assemble information from various sources.", "We need to compile a comprehensive database.", "C1", "verb"],
  ["comprise", "To consist of or be made up of.", "The committee will comprise ten senior members.", "C1", "verb"],
  ["concede", "To admit that something is true after denying it.", "The candidate refused to concede the close election.", "C1", "verb"],
  ["concrete", "Existing in a material or physical form.", "We need concrete evidence before making arrests.", "C1", "adjective"],
  ["condone", "To accept and allow bad behavior.", "The school does not condone violence of any kind.", "C1", "verb"],
  ["conduit", "A channel for conveying fluid or cables.", "The cables are protected inside a metal conduit.", "C1", "noun"],
  ["confine", "To keep or restrict within limits.", "Please confine your comments to the agenda topic.", "C1", "verb"],
  ["conflict", "A serious disagreement or argument.", "The two countries are in a bitter border conflict.", "C1", "noun"],
  ["conform", "To comply with rules or standards.", "All products must conform to safety regulations.", "C1", "verb"],
  ["confront", "To face up to and deal with a problem.", "We must confront these severe challenges directly.", "C1", "verb"],
  ["convey", "To communicate a message or transport something.", "Please convey my warm regards to your parents.", "C1", "verb"],
  ["conserve", "To protect something from harm or decay.", "We need to conserve water during dry summers.", "C1", "verb"],
  ["consist", "To be composed or made up of.", "Healthy diets consist of vegetables and grains.", "C1", "verb"],
  ["consoles", "Devices used for playing video games.", "Modern gaming consoles offer high-definition graphics.", "C1", "noun"],
  ["conspire", "To make secret plans jointly to commit a crime.", "They conspired to steal the famous painting.", "C1", "verb"],
  ["absolute", "Complete and unconditional.", "The monarch ruled with absolute power.", "C2", "adjective"],
  ["abyss", "A deep or seemingly bottomless chasm.", "The climber stared down into the dark abyss.", "C2", "noun"],
  ["acumen", "The ability to make good judgments.", "His business acumen led the startup to success.", "C2", "noun"],
  ["adverse", "Preventing success or development.", "The flight was cancelled due to adverse weather.", "C2", "adjective"],
  ["adhere", "To stick to a surface or follow a rule strictly.", "All members must adhere to the club's regulations.", "C2", "verb"],
  ["affinity", "A natural liking or sympathy for someone.", "She has a special affinity for classical art.", "C2", "noun"],
  ["agile", "Able to move quickly and easily.", "The agile gymnast performed a perfect flip.", "C2", "adjective"],
  ["alchemy", "A seemingly magical process of transformation.", "The chef's skill was a form of culinary alchemy.", "C2", "noun"],
  ["alias", "A false identity used by a criminal.", "The spy traveled under a clever alias.", "C2", "noun"],
  ["allude", "To suggest or call attention to indirectly.", "The speaker did not allude to the scandal.", "C2", "verb"],
  ["aloof", "Not friendly or willing to take part.", "He stood aloof from the arguing crowd.", "C2", "adjective"],
  ["altitude", "The height of an object above sea level.", "The plane flew at a high altitude.", "C2", "noun"],
  ["altruism", "Disinterested and selfless concern for others.", "Her charity work was an act of pure altruism.", "C2", "noun"],
  ["ambient", "Relating to the immediate surroundings.", "We enjoyed the warm ambient light of the room.", "C2", "adjective"],
  ["amenity", "A desirable or useful feature of a place.", "The luxury hotel offered every modern amenity.", "C2", "noun"],
  ["amity", "A friendly relationship.", "The treaty was signed in a spirit of amity.", "C2", "noun"],
  ["amnesty", "An official pardon for political offenses.", "The government declared amnesty for all rebels.", "C2", "noun"],
  ["anarchy", "A state of disorder due to absence of authority.", "The collapse of the police led to total anarchy.", "C2", "noun"],
  ["anatomy", "The bodily structure of humans.", "Doctors study human anatomy for many years.", "C2", "noun"],
  ["anchor", "A heavy metal device used to secure a ship.", "They dropped the anchor in the quiet bay.", "C2", "noun"],
  ["angular", "Having sharp corners or angles.", "The modern building featured a bold angular design.", "C2", "adjective"],
  ["antidote", "A medicine taken to counteract a poison.", "Doctors searched for a rapid antidote to the venom.", "C2", "noun"],
  ["apex", "The highest point of something.", "The eagle built its nest at the mountain apex.", "C2", "noun"],
  ["apathy", "A lack of interest or enthusiasm.", "Widespread student apathy concerned the principal.", "C2", "noun"],
  ["applaud", "To show strong approval publicly.", "We applaud the government's brave decision.", "C2", "verb"],
  ["archaic", "Very old or old-fashioned.", "The school abandoned its archaic dress code rules.", "C2", "adjective"],
  ["arena", "A place for sports or public events.", "Thousands of fans gathered in the sports arena.", "C2", "noun"],
  ["artisan", "A worker skilled in a skilled trade.", "The artisan crafted beautiful wooden furniture.", "C2", "noun"],
  ["ascend", "To go or climb up.", "They watched the hot air balloon ascend slowly.", "C2", "verb"],
  ["ascent", "An instance of rising or climbing up.", "The mountain ascent took five exhausting hours.", "C2", "noun"],
  ["aspire", "To direct one's hopes towards achieving.", "Young athletes aspire to win Olympic medals.", "C2", "verb"],
  ["assert", "To state a fact confidently and forcefully.", "The lawyer continued to assert her client's innocence.", "C2", "verb"],
  ["asthma", "A condition marked by breathing difficulty.", "Cold weather can trigger a painful asthma attack.", "C2", "noun"],
  ["asylum", "Protection granted by a nation to refugees.", "They fled the war and requested political asylum.", "C2", "noun"],
  ["atlas", "A book of maps or charts.", "He opened the old atlas to locate the island.", "C2", "noun"],
  ["atom", "The basic unit of a chemical element.", "A water molecule has two hydrogen atoms.", "C2", "noun"],
  ["audit", "An official inspection of accounts.", "The tax department ordered an official audit.", "C2", "noun"],
  ["aura", "A distinctive atmosphere surrounding a person.", "The old library has a quiet, majestic aura.", "C2", "noun"],
  ["aurora", "A natural light display in the polar sky.", "They traveled north to photograph the aurora.", "C2", "noun"],
  ["austere", "Severe or strict in manner or appearance.", "The monk lived a quiet, austere life in the hills.", "C2", "adjective"],
  ["authentic", "Of undisputed origin or genuine.", "They served authentic Italian pizza at the dinner.", "C2", "adjective"],
  ["autonomy", "The right of self-government.", "The region requested greater political autonomy.", "C2", "noun"],
  ["avalanche", "A mass of snow sliding down a mountain.", "The skiers escaped a dangerous snow avalanche.", "C2", "noun"],
  ["axiom", "A statement accepted as established truth.", "The geometric proof was based on a simple axiom.", "C2", "noun"],
  ["axis", "An imaginary line about which a body rotates.", "The earth rotates on its tilted axis daily.", "C2", "noun"],
  ["azure", "Bright blue in color like a cloudless sky.", "The warm ocean water was a brilliant azure.", "C2", "adjective"],
  ["backup", "A copy of files to protect against loss.", "Always keep a secure backup of your files.", "C2", "noun"],
  ["baffle", "To totally confuse or perplex.", "The complex puzzle managed to baffle the expert.", "C2", "verb"],
  ["banish", "To send someone away as official punishment.", "The king decided to banish the rebel leader.", "C2", "verb"],
  ["barren", "Land too poor to produce vegetation.", "They crossed the dry, barren mountain landscape.", "C2", "adjective"],
];

const portugueseDefinitions: Record<string, string> = {
  apple: 'Uma fruta redonda com casca vermelha, verde ou amarela.',
  book: 'Um conjunto de páginas escritas que você lê.',
  city: 'Uma cidade grande onde muitas pessoas vivem e trabalham.',
  family: 'Um grupo de pessoas relacionadas entre si.',
  friend: 'Uma pessoa que você gosta e conhece bem.',
  happy: 'Sentir-se bem ou satisfeito.',
  listen: 'Dar atenção a um som ou a alguém que fala.',
  morning: 'A parte cedo do dia.',
  school: 'Um lugar onde os alunos aprendem.',
  water: 'Um líquido claro que as pessoas bebem.',
  chair: 'Um assento para uma pessoa.',
  door: 'Uma coisa que você abre para entrar ou sair de um cômodo.',
  food: 'Coisas que pessoas ou animais comem.',
  house: 'Um prédio onde as pessoas moram.',
  mother: 'Uma parental feminina.',
  music: 'Sons feitos por vozes ou instrumentos.',
  phone: 'Um aparelho usado para ligar ou mandar mensagem.',
  picture: 'Uma imagem, desenho ou fotografia.',
  table: 'Um móvel com uma superfície plana.',
  work: 'Um trabalho ou atividade que exige esforço.',
  borrow: 'Usar algo e devolver depois.',
  careful: 'Tomar cuidado para evitar erros ou perigo.',
  decide: 'Escolher depois de pensar nas opções.',
  explain: 'Fazer algo claro ou fácil de entender.',
  healthy: 'Bom para o corpo ou não doente.',
  improve: 'Ficar melhor ou fazer algo melhor.',
  mistake: 'Algo que não está correto.',
  simple: 'Fácil de entender ou fazer.',
  travel: 'Ir de um lugar para outro.',
  weather: 'A temperatura, vento, chuva ou sol do lado de fora.',
  arrive: 'Chegar a um lugar.',
  choose: 'Selecionar uma coisa entre várias opções.',
  describe: 'Dizer como algo ou alguém é.',
  favorite: 'Gostado mais do que os outros.',
  invite: 'Pedir que alguém venha para um evento.',
  journey: 'Uma viagem de um lugar a outro.',
  noisy: 'Fazendo muito barulho.',
  protect: 'Manter alguém ou algo seguro.',
  repair: 'Consertar algo que está quebrado.',
  useful: 'Útil ou prático.',
  achieve: 'Conseguir fazer algo com esforço.',
  benefit: 'Um efeito bom ou vantagem.',
  confident: 'Sentir-se seguro sobre sua habilidade.',
  manage: 'Controlar ou organizar algo com sucesso.',
  opinion: 'O que alguém pensa ou acredita sobre algo.',
  prevent: 'Impedir que algo aconteça.',
  reduce: 'Tornar algo menor ou menos.',
  reliable: 'Capaz de ser confiável ou dependente.',
  struggle: 'Ter dificuldade para fazer algo.',
  support: 'Ajudar alguém ou concordar com uma ideia.',
  approach: 'Uma maneira de fazer ou pensar sobre algo.',
  balance: 'Um estado em que diferentes coisas têm a quantidade certa.',
  compare: 'Olhar duas coisas e ver semelhanças ou diferenças.',
  develop: 'Crescer ou tornar-se mais avançado.',
  encourage: 'Dar esperança ou confiança a alguém.',
  focus: 'Dar atenção a uma coisa.',
  involve: 'Incluir alguém ou algo.',
  likely: 'Esperado de acontecer ou ser verdade.',
  recognize: 'Conhecer alguém ou algo de antes.',
  suggest: 'Oferecer uma ideia ou plano.',
  accomplish: 'Completar algo com sucesso.',
  challenge: 'Uma tarefa difícil que testa habilidade.',
  consequence: 'Um resultado de uma ação ou situação.',
  estimate: 'Adivinhar um valor com base nas informações disponíveis.',
  evidence: 'Fatos ou sinais que mostram que algo é verdadeiro.',
  maintain: 'Manter algo no mesmo nível ou condição.',
  negotiate: 'Discutir para chegar a um acordo.',
  prioritize: 'Decidir o que é mais importante.',
  remarkable: 'Incomum ou impressionante de forma que as pessoas notam.',
  sustainable: 'Capaz de continuar por muito tempo sem causar dano.',
  accurate: 'Correto e sem erros.',
  adapt: 'Mudar para se ajustar a uma nova situação.',
  convince: 'Fazer alguém acreditar ou concordar.',
  evaluate: 'Julgar o valor ou qualidade de algo.',
  framework: 'Uma estrutura básica para ideias ou trabalho.',
  generate: 'Produzir ou criar algo.',
  insight: 'Uma compreensão clara de algo.',
  objective: 'Um objetivo ou propósito.',
  resolve: 'Resolver um problema ou dificuldade.',
  tension: 'Uma sensação de estresse ou pressão.',
  ambiguous: 'Tendo mais de um significado possível.',
  coherent: 'Claro, lógico e fácil de entender.',
  compelling: 'Muito interessante ou convincente.',
  concise: 'Usar poucas palavras mantendo clareza.',
  deteriorate: 'Ficar pior ao longo do tempo.',
  implement: 'Colocar um plano ou sistema em ação.',
  leverage: 'Usar algo de forma eficaz para obter um resultado.',
  mitigate: 'Tornar um problema menos grave.',
  resilient: 'Capaz de se recuperar rapidamente após dificuldade.',
  substantial: 'Grande em quantidade, valor ou importância.',
  allocate: 'Decidir como recursos ou tempo devem ser usados.',
  articulate: 'Expressar uma ideia claramente.',
  constraint: 'Um limite ou restrição.',
  cultivate: 'Desenvolver uma habilidade ou hábito com cuidado.',
  diminish: 'Ficar ou fazer algo menor.',
  formulate: 'Criar ou preparar algo cuidadosamente.',
  inherent: 'Existente como parte natural de algo.',
  pragmatic: 'Focado em resultados práticos.',
  refine: 'Melhorar algo fazendo pequenas mudanças.',
  scrutiny: 'Exame cuidadoso e detalhado.',
  ephemeral: 'Durar apenas por um curto período.',
  exacerbate: 'Tornar uma situação ruim pior.',
  incongruous: 'Estranho porque não se encaixa no ambiente.',
  meticulous: 'Muito cuidadoso e atento aos detalhes.',
  nuance: 'Uma pequena, mas importante diferença de significado.',
  paradigm: 'Um modelo típico ou maneira de pensar sobre algo.',
  proliferation: 'Um aumento rápido no número de algo.',
  scrutinize: 'Examinar algo com muita atenção.',
  ubiquitous: 'Presente ou encontrado em todos os lugares.',
  unequivocal: 'Claro e sem deixar dúvida.',
  aberration: 'Algo incomum que difere do normal.',
  conflate: 'Combinar duas ideias como se fossem a mesma.',
  dissonance: 'Falta de acordo ou harmonia.',
  intractable: 'Muito difícil de controlar ou resolver.',
  labyrinthine: 'Complicado e confuso como um labirinto.',
  obfuscate: 'Tornar algo pouco claro ou difícil de entender.',
  perfunctory: 'Feito rapidamente e sem cuidado real.',
  quintessential: 'Representando o exemplo mais típico.',
  tacit: 'Entendido sem ser dito diretamente.',
  vindicate: 'Provar que alguém ou algo estava certo.',
  baby: 'Um bebê ou criança muito nova.',
  ball: 'Um objeto redondo usado em jogos.',
  bank: 'Um lugar onde as pessoas guardam dinheiro.',
  bath: 'O ato de lavar o corpo.',
  beer: 'Uma bebida alcoólica feita de grãos.',
  bird: 'Um animal com penas e asas.',
  blue: 'Uma cor como a do céu limpo.',
  boat: 'Um pequeno veículo para navegar na água.',
  body: 'A estrutura física de uma pessoa.',
  busy: 'Com muitas coisas para fazer.',
  cake: 'Um alimento doce assado.',
  card: 'Um pequeno pedaço de papel rígido.',
  cat: 'Um pequeno animal doméstico.',
  cold: 'Que tem uma temperatura baixa.',
  coat: 'Uma peça de roupa externa.',
  cup: 'Um pequeno recipiente usado para beber.',
  dark: 'Com pouca ou nenhuma luz.',
  date: 'Um dia específico do mês.',
  day: 'Um período de vinte e quatro horas.',
  dog: 'Um animal comum mantido como animal de estimação.',
  draw: 'Fazer um desenho com uma caneta ou lápis.',
  drink: 'Levar líquido à boca.',
  easy: 'Não difícil de fazer.',
  egg: 'Um objeto oval produzido por uma ave.',
  eye: 'O órgão da visão.',
  face: 'A parte frontal da cabeça.',
  fire: 'Calor e luz provenientes da queima.',
  fish: 'Um animal que vive na água.',
  game: 'Uma atividade jogada por diversão.',
  girl: 'Uma criança do sexo feminino.',
  hair: 'Os fios finos na cabeça.',
  hand: 'A parte do braço abaixo do pulso.',
  head: 'A parte superior do corpo.',
  hot: 'Com temperatura elevada.',
  kind: 'Amigável e generoso.',
  land: 'A parte sólida da terra.',
  life: 'O período de estar vivo.',
  love: 'Um forte sentimento de afeto.',
  milk: 'Um líquido branco produzido por vacas.',
  name: 'Uma palavra pela qual uma pessoa é conhecida.',
  nice: 'Agradável ou atraente.',
  paper: 'Material usado para escrever.',
  rain: 'Água caindo do céu.',
  road: 'Uma rota para veículos e pessoas.',
  shoe: 'Uma cobertura para o pé.',
  song: 'Uma pequena peça musical com palavras.',
  star: 'Um pequeno ponto brilhante no céu noturno.',
  tree: 'Uma planta alta com um tronco.',
  wind: 'Um movimento natural do ar.',
  year: 'Um período de 365 dias.',
  angry: 'Sentir forte desagrado ou irritação.',
  beach: 'Costa arenosa junto ao oceano.',
  bread: 'Alimento assado feito de farinha e água.',
  camel: 'Um animal grande com corcovas.',
  candy: 'Alimento doce feito com açúcar.',
  cheap: 'Baixo em preço ou custo.',
  clean: 'Livre de sujeira ou marcas.',
  cloud: 'Uma massa branca no céu.',
  count: 'Determinar o número de itens.',
  cry: 'Derramar lágrimas devido à tristeza.',
  dance: 'Mover-se ao ritmo da música.',
  dirty: 'Não limpo ou coberto de lama.',
  dream: 'Pensamentos que ocorrem durante o sono.',
  dress: 'Uma peça de vestuário de peça única para mulheres.',
  early: 'Antes do horário habitual ou esperado.',
  earth: 'O planeta no qual vivemos.',
  enjoy: 'Sentir prazer em alguma coisa.',
  fight: 'Envolver-se em batalha ou luta física.',
  fruit: 'Produto doce de uma planta.',
  glass: 'Um material duro e transparente.',
  grass: 'Vegetação verde nos gramados.',
  green: 'Uma cor como a da grama.',
  heart: 'O órgão que bombeia o sangue.',
  heavy: 'Que tem grande peso.',
  horse: 'Um animal grande usado para montaria.',
  knife: 'Uma ferramenta usada para cortar.',
  laugh: 'Fazer sons de divertimento.',
  light: 'O agente natural que estimula a visão.',
  lunch: 'Uma refeição feita no meio do dia.',
  month: 'Um dos doze períodos de um ano.',
  neck: 'Parte do corpo que conecta a cabeça e os ombros.',
  onion: 'Um vegetal redondo com cheiro forte.',
  park: 'Uma área verde pública.',
  plant: 'Um ser vivo que cresce na terra.',
  plate: 'Um prato plano para comida.',
  pocket: 'Uma pequena bolsa em roupas.',
  quick: 'Mover-se ou fazer algo rápido.',
  quiet: 'Fazendo muito pouco barulho.',
  river: 'Um grande fluxo natural de água.',
  salt: 'Substância branca usada para dar sabor aos alimentos.',
  sleep: 'Um estado natural de descanso.',
  slow: 'Não se mover ou agir rapidamente.',
  small: 'Pequeno em tamanho ou quantidade.',
  smoke: 'Nuvem produzida pela queima.',
  snow: 'Chuva congelada caindo em flocos.',
  spoon: 'Uma ferramenta usada para comer sopa.',
  sport: 'Uma atividade física ou jogo.',
  stone: 'Um pequeno pedaço de rocha.',
  train: 'Uma série de vagões de ferrovia conectados.',
  valley: 'Área baixa de terra entre colinas.',
  accent: 'Uma forma distinta de pronunciar um idioma.',
  active: 'Envolver-se em atividades energeticamente físicas.',
  advice: 'Orientação ou recomendações oferecidas.',
  afraid: 'Sentir medo ou ansiedade.',
  agency: 'Uma empresa que representa outros.',
  amount: 'Uma quantidade de alguma coisa.',
  border: 'A fronteira entre dois países.',
  brain: 'O órgão do pensamento dentro da cabeça.',
  breeze: 'Um vento suave e agradável.',
  bridge: 'Uma estrutura construída sobre um rio.',
  camera: 'Um dispositivo para tirar fotografias.',
  candle: 'Um cilindro de cera com um pavio central.',
  career: 'Uma profissão seguida por um período significativo.',
  castle: 'Um grande edifício fortificado.',
  chance: 'Uma possibilidade de algo acontecer.',
  choice: 'O ato de escolher entre opções.',
  clever: 'Rápido para entender ou aprender.',
  corner: 'O lugar onde duas ruas se encontram.',
  cousin: 'O filho de um tio ou tia.',
  danger: 'A possibilidade de sofrer danos.',
  degree: 'Uma qualificação acadêmica.',
  desert: 'Uma área de terra seca e arenosa.',
  detail: 'Um fato ou item individual.',
  dinner: 'A principal refeição do dia, comida à noite.',
  double: 'Consistir em duas coisas iguais.',
  driver: 'Uma pessoa que opera um veículo.',
  empty: 'Que não contém nada ou está vago.',
  engine: 'Uma máquina que converte energia em movimento.',
  escape: 'Libertar-se do perigo.',
  event: 'Uma ocasião social ou pública planejada.',
  expert: 'Uma pessoa com conhecimento especial.',
  factor: 'Uma influência que contribui para um resultado.',
  flight: 'Uma viagem realizada pelo ar.',
  forest: 'Uma grande área coberta de árvores.',
  future: 'Um período de tempo posterior ao presente.',
  garden: 'Um pedaço de terra junto a uma casa para cultivar plantas.',
  growth: 'O processo de aumento de tamanho.',
  height: 'A medição da base ao topo.',
  hidden: 'Mantido fora de vista ou oculto.',
  hungry: 'Sentir necessidade de alimento.',
  insect: 'Uma pequena criatura com seis pernas.',
  island: 'Um pedaço de terra cercado por água.',
  market: 'Um encontro regular para compra e venda.',
  nature: 'Os fenômenos do mundo físico.',
  option: 'Uma coisa que é ou pode ser escolhida.',
  parent: 'Um pai ou uma mãe.',
  pencil: 'Um instrumento para escrever ou desenhar.',
  reason: 'Uma causa ou explicação para um evento.',
  shadow: 'Uma área escura produzida pelo bloqueio da luz.',
  sudden: 'Ocorrer ou ser feito de forma rápida e inesperada.',
  acquire: 'Comprar ou obter um ativo.',
  adjust: 'Alterar ligeiramente para alcançar ajuste.',
  analyze: 'Examinar metodicamente.',
  annual: 'Que ocorre uma vez a cada ano.',
  asset: 'Uma qualidade ou coisa útil ou valiosa.',
  capture: 'Registrar ou expressar com precisão.',
  catalog: 'Uma lista completa de itens em ordem sistemática.',
  citizen: 'Um sujeito legalmente reconhecido de um estado.',
  classic: 'Julgado ao longo do tempo como sendo de alta qualidade.',
  climate: 'As condições climáticas prevalecentes em uma área.',
  closure: 'Uma sensação de resolução ou conclusão.',
  cluster: 'Um grupo de coisas semelhantes posicionadas próximas.',
  collect: 'Reunir coisas.',
  columns: 'Divisões verticais de uma página ou texto.',
  combat: 'Tomar medidas para reduzir ou prevenir.',
  command: 'Uma diretiva ou ordem de autoridade.',
  complex: 'Consistir em muitas partes diferentes e conectadas.',
  conduct: 'Organizar e realizar uma atividade.',
  consent: 'Permissão para que algo aconteça.',
  context: 'As circunstâncias que formam o cenário de um evento.',
  crucial: 'De grande importância ou decisivo.',
  current: 'Pertencente ao momento presente.',
  custom: 'Uma forma tradicional de se comportar.',
  decade: 'Um período de dez anos.',
  decline: 'Tornar-se menor, menor número ou menos.',
  defend: 'Proteger de danos ou perigos.',
  defense: 'Ação tomada para se proteger contra ataques.',
  deficit: 'Um excesso de despesas sobre as receitas.',
  density: 'O grau de compactação de uma substância.',
  deposit: 'Uma soma em dinheiro paga em uma conta bancária.',
  derive: 'Obter algo de uma fonte específica.',
  dessert: 'Alimento doce comido ao final de uma refeição.',
  detect: 'Descobrir ou identificar a presença de.',
  device: 'Um instrumento fabricado para um propósito específico.',
  diary: 'Um livro no qual se mantém um registro diário.',
  digital: 'Expresso em dígitos numéricos, especialmente binários.',
  dilemma: 'Uma situação ou escolha difícil.',
  dismiss: 'Decidir que algo não é importante.',
  display: 'Mostrar ou exibir publicamente.',
  diverse: 'Que apresenta grande variedade.',
  dynamic: 'Caracterizado por constante mudança ou progresso.',
  edition: 'Uma versão específica de um texto publicado.',
  elastic: 'Capaz de recuperar a forma normal depois de esticar.',
  element: 'Uma parte essencial de alguma coisa.',
  elegant: 'Gracioso e estiloso na aparência.',
  emerald: 'Uma pedra preciosa verde brilhante.',
  emerge: 'Tornar-se aparente ou proeminente.',
  emotion: 'Um sentimento forte como alegria.',
  empire: 'Um grande grupo de estados governados por um único monarca.',
  faculty: 'Uma capacidade mental ou física inerente.',
  abstract: 'Existente no pensamento, mas sem existência física.',
  acoustic: 'Relativo ao som ou à audição.',
  acute: 'Grave ou intenso em alto grau.',
  adjacent: 'Próximo ou contíguo a algo mais.',
  advocate: 'Uma pessoa que apoia publicamente uma causa.',
  alliance: 'Uma união ou associação formada para benefício mútuo.',
  alloy: 'Um metal feito pela combinação de dois ou mais elementos metálicos.',
  amateur: 'Uma pessoa que se dedica a uma atividade de forma não remunerada.',
  analogy: 'Uma comparação entre uma coisa e outra.',
  analyst: 'Uma pessoa que realiza análises metódicas.',
  ancestor: 'Uma pessoa da qual se descende.',
  anomaly: 'Algo que se desvia do que é padrão.',
  approval: 'A crença de que alguém ou algo é bom.',
  arbitrary: 'Baseado em escolha aleatória em vez de razão.',
  archive: 'Uma coleção de documentos históricos.',
  aroma: 'Um cheiro agradável e característico.',
  artifact: 'Um objeto feito por um ser humano de interesse histórico.',
  boundary: 'Uma linha que marca o limite de uma área.',
  breach: 'O ato de quebrar uma lei ou acordo.',
  brilliant: 'Excepcionalmente inteligente ou talentoso.',
  browse: 'Examinar bens ou informações de forma casual.',
  calendar: 'Um gráfico que mostra os dias e meses.',
  capsule: 'Um pequeno invólucro gelatinoso que encerra o medicamento.',
  casual: 'Relaxado e despreocupado.',
  catalyst: 'Um evento ou pessoa que provoca mudanças.',
  caution: 'Cuidado tomado para evitar perigos ou erros.',
  cavity: 'Um espaço vazio dentro de um objeto sólido.',
  ceramic: 'Argila cozida a altas temperaturas.',
  chaotic: 'Em um estado de completa confusão.',
  chronic: 'Que persiste por muito tempo.',
  circuit: 'Um caminho completo para a corrente elétrica.',
  citation: 'Uma referência a uma fonte acadêmica.',
  clarify: 'Tornar uma afirmação menos confusa.',
  cognitive: 'Relativo à atividade intelectual.',
  compact: 'Próximos e organizadamente compactados.',
  compile: 'Reunir informações de várias fontes.',
  comprise: 'Consistir em ou ser composto por.',
  concede: 'Admitir que algo é verdadeiro após negá-lo.',
  concrete: 'Existente em forma material ou física.',
  condone: 'Aceitar e permitir mau comportamento.',
  conduit: 'Um canal para transporte de fluidos ou cabos.',
  confine: 'Manter ou restringir dentro de limites.',
  conflict: 'Um desentendimento ou discussão séria.',
  conform: 'Cumprir regras ou padrões.',
  confront: 'Encarar e lidar com um problema.',
  convey: 'Comunicar uma mensagem ou transportar algo.',
  conserve: 'Proteger algo contra danos ou deterioração.',
  consist: 'Ser composto ou constituído por.',
  consoles: 'Dispositivos usados para jogar videogame.',
  conspire: 'Fazer planos secretos conjuntamente para cometer um crime.',
  absolute: 'Completo e incondicional.',
  abyss: 'Um abismo profundo ou aparentemente sem fundo.',
  acumen: 'A habilidade de tomar boas decisões rapidamente.',
  adverse: 'Que impede o sucesso ou desenvolvimento.',
  adhere: 'Aderir a uma superfície ou seguir rigidamente uma regra.',
  affinity: 'Uma simpatia ou afeição natural por alguém ou algo.',
  agile: 'Capaz de se mover de forma rápida e fácil.',
  alchemy: 'Um processo aparentemente mágico de transformação.',
  alias: 'Uma identidade falsa usada por um criminoso.',
  allude: 'Sugerir ou chamar a atenção indiretamente.',
  aloof: 'Não amigável ou que não quer participar.',
  altitude: 'A altura de um objeto acima do nível do mar.',
  altruism: 'Preocupação desinteressada e altruísta pelos outros.',
  ambient: 'Relativo aos arredores imediatos.',
  amenity: 'Uma característica desejável ou útil de um lugar.',
  amity: 'Uma relação amigável.',
  amnesty: 'Um perdão oficial por crimes políticos.',
  anarchy: 'Estado de desordem devido à ausência de autoridade.',
  anatomy: 'A estrutura corporal de humanos ou outros organismos.',
  anchor: 'Um dispositivo pesado de metal usado para prender um navio.',
  angular: 'Que apresenta cantos afiados ou ângulos.',
  antidote: 'Um medicamento tomado para neutralizar um veneno.',
  apex: 'O ponto mais alto de alguma coisa.',
  apathy: 'Falta de interesse ou entusiasmo.',
  applaud: 'Mostrar forte aprovação publicamente.',
  archaic: 'Muito antigo ou fora de moda.',
  arena: 'Um lugar para esportes ou eventos públicos.',
  artisan: 'Um trabalhador habilidoso em um ofício especializado.',
  ascend: 'Ir ou subir.',
  ascent: 'Um exemplo de subida ou escalada.',
  aspire: 'Direcionar as esperanças para alcançar algo.',
  assert: 'Declarar um fato de forma confiante e enérgica.',
  asthma: 'Condição caracterizada por dificuldade respiratória.',
  asylum: 'Proteção concedida por uma nação a refugiados.',
  atlas: 'Um livro de mapas ou gráficos.',
  atom: 'A unidade básica de um elemento químico.',
  audit: 'Uma inspeção oficial de contas.',
  aura: 'Uma atmosfera distinta que cerca uma pessoa.',
  aurora: 'Exibição de luz natural no céu polar.',
  austere: 'Grave ou rigoroso na atitude ou aparência.',
  authentic: 'De origem indiscutível ou genuíno.',
  autonomy: 'O direito de autogoverno.',
  avalanche: 'Massa de neve deslizando montanha abaixo.',
  axiom: 'Uma afirmação aceita como verdade estabelecida.',
  axis: 'Linha imaginária sobre a qual um corpo gira.',
  azure: 'Cor azul brilhante como um céu sem nuvens.',
  backup: 'Cópia de arquivos para proteção contra perda.',
  baffle: 'Confundir ou perplexar totalmente.',
  banish: 'Enviar alguém embora como punição oficial.',
  barren: 'Terra muito pobre para produzir vegetação.',
};

export const fallbackWords: VocabWord[] = rawWords.map(
  ([word, definition, example, level, partOfSpeech], index) => ({
    id: index + 1,
    word,
    definition: definition,
    definition_pt: portugueseDefinitions[word] ?? definition,
    example,
    example_with_blank: blankExample(example, word),
    level,
    part_of_speech: partOfSpeech,
  }),
);

export function createEmptyStudyState(clientId = ""): StudyState {
  return {
    clientId,
    wordProgress: {},
    history: [],
    xp: 0,
    level: 1,
    currentStreak: 0,
    bestStreak: 0,
    lastStudyDate: null,
    totalAttempts: 0,
    correctAttempts: 0,
  };
}

export function blankExample(example: string, word: string): string {
  const escaped = word.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  return example.replace(new RegExp(`\\b${escaped}\\b`, "i"), "_____");
}

export function normalizeAnswer(answer: string): string {
  return answer.toLowerCase().trim().replace(/[^a-z]/g, "");
}

export function scrambleWord(word: string): string[] {
  const letters = word.split("");

  for (let i = letters.length - 1; i > 0; i -= 1) {
    const j = Math.floor(Math.random() * (i + 1));
    [letters[i], letters[j]] = [letters[j], letters[i]];
  }

  if (letters.join("") === word && letters.length > 2) {
    [letters[0], letters[1]] = [letters[1], letters[0]];
  }

  return letters;
}

export function isDue(progress?: WordProgress, now = new Date()): boolean {
  if (!progress?.nextReviewAt) {
    return false;
  }

  return new Date(progress.nextReviewAt).getTime() <= now.getTime();
}

export function selectNextWord(
  words: VocabWord[],
  level: Level,
  mode: PracticeMode,
  progress: Record<string, WordProgress>,
  avoidWordId?: number | null,
): VocabWord | null {
  const sameLevel = mode === "review" || mode === "seen"
    ? words.filter((word) => word.level === level)
    : words.filter((word) => word.level === level && !(progress[word.id]?.correctAttempts > 0));

  const due = mode === "review" || mode === "seen"
    ? words.filter((word) => isDue(progress[word.id]))
    : words.filter((word) => isDue(progress[word.id]) && !(progress[word.id]?.correctAttempts > 0));

  let candidates = sameLevel;

  if (mode === "review") {
    candidates = sameLevel.filter((word) => {
      const item = progress[word.id];
      return isDue(item) || (item?.incorrectAttempts ?? 0) > (item?.correctAttempts ?? 0);
    });
  }

  if (mode === "seen") {
    candidates = sameLevel.filter((word) => (progress[word.id]?.attempts ?? 0) > 0);
  }

  if (mode === "auto") {
    candidates = due.length > 0 ? due : sameLevel.filter((word) => !progress[word.id]?.learned);
  }

  if (candidates.length === 0) {
    const fallbackSameLevel = words.filter((word) => word.level === level);
    candidates = sameLevel.length > 0 
      ? sameLevel 
      : (mode === "review" || mode === "seen" ? fallbackSameLevel : fallbackSameLevel.filter((word) => !(progress[word.id]?.correctAttempts > 0)));
  }

  if (candidates.length === 0) {
    return null;
  }

  const filtered = candidates.length > 1 ? candidates.filter((word) => word.id !== avoidWordId) : candidates;
  const weighted = filtered.map((word) => {
    const item = progress[word.id];
    let weight = 2;

    if (!item) {
      weight += mode === "review" ? 0 : 3;
    } else {
      weight += Math.min(12, item.incorrectAttempts * 3);
      weight += Math.max(0, 3 - item.streakCorrect);
      weight += isDue(item) ? 8 : 0;
      weight -= item.learned ? 1 : 0;
    }

    return { word, weight: Math.max(1, weight) };
  });

  const total = weighted.reduce((sum, item) => sum + item.weight, 0);
  let roll = Math.random() * total;

  for (const item of weighted) {
    roll -= item.weight;

    if (roll <= 0) {
      return item.word;
    }
  }

  return weighted[0]?.word ?? null;
}

export function calculateScore(level: Level, seconds: number, hintsUsed: boolean, combo: number): number {
  const baseByLevel: Record<Level, number> = {
    A1: 8,
    A2: 10,
    B1: 12,
    B2: 15,
    C1: 18,
    C2: 22,
  };
  const speedBonus = Math.max(0, 20 - Math.min(20, seconds));
  const comboBonus = Math.min(20, combo * 2);
  const score = baseByLevel[level] + speedBonus + comboBonus;

  return hintsUsed ? Math.ceil(score * 0.7) : score;
}

export function dateKey(date = new Date()): string {
  const year = date.getFullYear();
  const month = String(date.getMonth() + 1).padStart(2, "0");
  const day = String(date.getDate()).padStart(2, "0");

  return `${year}-${month}-${day}`;
}

export function yesterdayKey(): string {
  const yesterday = new Date();
  yesterday.setDate(yesterday.getDate() - 1);

  return dateKey(yesterday);
}

export function addMinutes(date: Date, minutes: number): string {
  const copy = new Date(date);
  copy.setMinutes(copy.getMinutes() + minutes);

  return copy.toISOString();
}

export function addDays(date: Date, days: number): string {
  const copy = new Date(date);
  copy.setDate(copy.getDate() + days);

  return copy.toISOString();
}
